---
title: "Opening up the court (surface) in tennis grand slams"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    number_sections: yes
header-includes:
  - \usepackage{hyperref}
abstract: "IDK writing is hard"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message = FALSE)
library(deuce)
library(dplyr)
library(tidyr)
library(ggplot2)
library(forcats)
library(stringr)
library(knitr)
library(kableExtra)
library(gridExtra)
library(grid)
library(MASS)
library(ggrepel)
library(broom)
library(lme4)
library(cowplot)
library(ggpubr)
library(reshape2)


## To change into library(courtsports)
devtools::load_all("../..")

```


```{r data-cleaning, include = FALSE}
data(gs)
data(gs_players)
data(gs_partial)
data(gs_partial_players)
```

```{r graphing-parameters, include = FALSE}
# my_theme <-  theme_bw() + # White background, black and white theme
#   theme(axis.text = element_text(size = 12),
#         text = element_text(size = 14,
#         family="serif"),
#         plot.title = element_text(hjust = 0.5, size=16))

my_theme <-  theme_bw() + # White background, black and white theme
  theme(axis.text = element_text(size = 24),
        text = element_text(size = 28,
        family="serif"),
        plot.title = element_text(hjust = 0.5, size=34),
        plot.subtitle = element_text(hjust = 0.5))

tournament_colors <- c("#0297DB", "#b06835", "#0C2340", "#54008b")
league_colors <- c("#0C2340", "#902BA3")
win_colors <- c("#336699", "#339966")

# with yellow for us
tournament_colors <- c("#0297DB", "#b06835", "#ffe500", "#54008b")

graphic_width_long <- 16
graphic_width_short <- 12

```


```{r modelling, eval = FALSE}
## HIERARCHICAL MODELLING
## NOT RUN
## WARNING: Takes about 1 HOUR

gs_players$name_int = as.integer(as.factor(gs_players$name))
gs_players$hand_fac = as.factor(gs_players$hand)
gs_players$ioc_fac = as.factor(gs_players$ioc)
gs_players$atp = gs_players$league == "ATP"
gs_players$year_fac = as.factor(gs_players$year)
gs_players$late_round = gs_players$round >= "R16"
gs_players$seeded = gs_players$rank <= 32
gs_players$opponent_seeded = gs_players$opponent_rank <= 32

set.seed(091418)
nocourt_logistic = glm(did_win ~ ioc_fac + late_round + log(rank) + log(opponent_rank) + year_fac + atp, data = gs_players, family = "binomial")
base_logistic = glm(did_win ~ ioc_fac +  tournament + late_round + log(rank) + log(opponent_rank) + year_fac + atp, data = gs_players, family = "binomial")
country_logistic = glmer(did_win ~ late_round + log(rank) + log(opponent_rank) + year_fac + atp + (0 + tournament |ioc_fac), data = gs_players, family = "binomial")
ind_logistic = glmer(did_win ~  ioc_fac + late_round + log(rank) + log(opponent_rank) + year_fac + atp + (0 + tournament |name_int), data = gs_players, family = "binomial")
ind_logistic_noioc = glmer(did_win ~ late_round + log(rank) + log(opponent_rank) + year_fac + atp + (0 + tournament |name_int), data = gs_players, family = "binomial")
ind_int_logistic = glmer(did_win ~ late_round + log(rank) + log(opponent_rank) + year_fac + atp + tournament + (1|name_int), data = gs_players, family = "binomial")
ind_year_logistic = glmer(did_win ~ late_round + log(rank) + log(opponent_rank) + atp + tournament + (0+year_fac|name_int), data = gs_players, family = "binomial")
n_aces_mod = lmer(n_aces ~ late_round + log(rank) + log(opponent_rank) + year_fac + atp + (0 + tournament |name), data = gs_partial_players)
n_winners_mod = lmer(n_winners ~ late_round + log(rank) + log(opponent_rank) + year_fac + atp + (0 + tournament |name), data = gs_partial_players)
n_net_mod = lmer(n_netpt_w ~ late_round + log(rank) + log(opponent_rank) + year_fac + atp + (0 + tournament |name), data = gs_partial_players)
n_ue_mod = lmer(n_ue ~ late_round + log(rank) + log(opponent_rank) + year_fac + atp + (0 + tournament |name), data = gs_partial_players)


```


# Data and EDA {#sec:data-eda}

## Data {#sec:data}




```{r tab-data, include = TRUE, echo = FALSE}
w_id <- which(gs$winner_name == "Serena Williams")[1:2]
f_id <- which(gs$winner_name == "Roger Federer")[1:2]
n_id <- which(gs$winner_name == "Rafael Nadal")[1:2]
s_id <- which(gs$winner_name %in% c("Serena Williams", "Roger Federer", "Rafael Nadal"))
cols <- c("winner_name", "tourney_name", "year", "winner_ioc", "w_pointswon", "winner_rank", "l_pointswon", "loser_rank")
knitr::kable(gs[c(w_id, f_id, n_id), cols], format = "latex",
             row.names = FALSE, col.names = c("Winner", "Tournament", "Year", "W. IOC", "W. Points",  "W. Rank", "L. Points", "L. Rank"),
             caption = "\\label{tab:data}Example of the complete grand slam data.  It includes winner and loser attributes, match attributes, and tournament attributes.  Not all attributes are shown here.",
             booktabs = TRUE) %>% kable_styling(latex_options = "striped", "hold_position")
```



## Early Data Analysis {#sec:eda}

### Examining the distribution of points earned



```{r, fig.height=5, fig.width=10}

# grid.arrange(p1, p2, p3, ncol=3, widths=c(.25, .41, .34))


p2 <- ggplot(gs_players) + 
  geom_density(aes(pointswon, ..scaled..,
                   color=tournament, group=tournament, fill = tournament),
                                        size = 3, alpha = 0) + 
  scale_fill_manual(" ", values=tournament_colors,
                                labels = c("Australian Open (Plexicushion)",
                                           "French Open (Clay)",
                                           "US Open (DecoTurf)",
                                           "Wimbledon (Grass)")) + my_theme  +
  guides(fill = guide_legend(override.aes = list(size = 0, alpha = 1),
                              nrow=4, byrow=TRUE)) +
    theme(legend.position="bottom") +
    scale_color_manual(guide=FALSE, values=tournament_colors) +
  facet_wrap(~league, ncol=1) +
  labs(x = "Points", y = "Scaled density")

# 
# ggplot(gs_players) + geom_density(aes(pointswon, color=tournament, 
#                                             group=tournament, fill = tournament),
#                                         size = 3, alpha = 0) + 
#   scale_fill_manual(" ", values=tournament_colors,
#                                 labels = c("Australian Open\n(Plexicushion)",
#                                            "French Open\n(Clay)",
#                                            "US Open\n(DecoTurf)",
#                                            "Wimbledon\n(Grass)")) + my_theme  +
#   guides(fill = guide_legend(override.aes = list(size = 0, alpha = 1),
#                               nrow=2, byrow=TRUE)) +
#     theme(legend.position="bottom") +
#     scale_color_manual(guide=FALSE, values=tournament_colors) 



p1 <- ggplot(gs_players) + 
  geom_density(aes(pointswon, ..scaled..,
                   color = factor(did_win),
                   group = factor(did_win), fill = factor(did_win)),
               size = 3, alpha = 0) + 
  labs(x = "Points", y = " ") +
  scale_fill_manual(" ", values=win_colors, labels = c("Lost game", "Won game")) +
  scale_color_manual(guide = FALSE, values = win_colors) +
  facet_wrap(~league, ncol=1) + 
  my_theme +
  theme(legend.position="bottom",
        legend.spacing.y = unit(1.0, 'cm'),
        legend.margin=margin(t = 2.2, unit='cm'))  +
  guides(fill = guide_legend(override.aes = list(size = 0, alpha = 1),
                             nrow = 2,
                            byrow=TRUE),
        title.hjust = 5) 



grid.arrange(p2, p1, ncol=2) %>%
             # # top = textGrob("Distribution of points per match",
             # #                gp=gpar(fontsize=20, fontfamily="serif")),
             #  layout_matrix = rbind(c(2, 1),
             #                        c(2, 1),
             #                        c(NA, 1)),
             # heights=c(1, 3, .1)) %>%
  ggsave("plots/points_per_match.jpg", ., height=8, width=graphic_width_long)


# 
# ggarrange( p1, p2, nrow=1, ncol=2, common.legend = TRUE, legend="bottom") %>%
# grid.arrange(top = textGrob("Spaniards perform better on Clay: confirmed?",
#                             gp=gpar(fontsize=20, fontfamily="serif")),
#              bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
#                            # x = 0,
#                            # y = 0.5,
#                            just = "left",
#                            gp=gpar(fontfamily="serif")))
# 
# ggarrange( p1, p2, nrow=1, ncol=2, common.legend = TRUE, legend="bottom") %>%
#   ggsave("plots/spainards.jpg", ., height=7, width=16)

```


### Home court advantage 

```{r, fig.height=3.5, fig.width=10, fig.align='center'}
france_wins <- dplyr::filter(gs_players, ioc == "FRA", round < "QF") %>% 
  dplyr::group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

us_wins <- dplyr::filter(gs_players, ioc == "USA", round < "QF") %>% 
  dplyr::group_by(tournament, round) %>% 
  dplyr::summarize(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

aus_wins <- filter(gs_players, ioc == "AUS", round < "QF") %>% 
  group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

gbr_wins <- filter(gs_players, ioc == "GBR", round < "QF") %>% 
  group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))



our_alpha <- 0.5

p1<- ggplot(france_wins, aes(round, win_prop,
                             color=tournament, group=tournament,
                             alpha = tournament,
                             size = tournament)) + 
  # geom_line(size = 3) + 
  # geom_point() +
  labs(title = "French players",
       x = "", y = " ") + 
  geom_line(size=3) + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
scale_alpha_manual(guide = FALSE,
                   values = c(our_alpha, 1, our_alpha, our_alpha)) + 
scale_size_manual(guide = FALSE,
                   values = c(1, 3, 1, 1))

p2 <- ggplot(us_wins, aes(round, win_prop,
                          color=tournament, group=tournament,
                          alpha = tournament)) + 
  # geom_line() + 
  # geom_point() +
  labs(title = "USA players",
              x = "", y = " ") + 
       # x = "", y = "Win proportion") + 
    geom_line(size=3) + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
scale_alpha_manual(guide = FALSE,
                   values = c(our_alpha, our_alpha, 1, our_alpha))

p3 <- ggplot(aus_wins, aes(round, win_prop,
                           color=tournament, group=tournament, alpha = tournament)) + 
  # geom_line() + 
  # geom_point() +
  labs(title = "Aus. players",
       x = "", y = "Win proportion") + 
         # x = "", y = " ") + 
    geom_line(size=3) + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
scale_alpha_manual(guide = FALSE,
                   values = c(1, our_alpha, our_alpha, our_alpha))


p4 <- ggplot(gbr_wins, aes(round, win_prop, color=tournament,
                           group=tournament, fill = tournament,
                           alpha = tournament)) + 
  geom_line(size=3) + 
  labs(title = "British players",
       # x = "", y = "Win proportion") + 
       x = "", y = " ") + 
  scale_color_manual(" ", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme +
  guides(color = guide_legend(override.aes = list(size = 7)))  + 
scale_alpha_manual(guide = FALSE,
                   values = c(our_alpha, our_alpha, our_alpha, 1))

# 
# + 
#   geom_line() + 
#   # geom_point() +
#   labs(title = "British players",
#        x = "", y = "Win proportion") + 
#   scale_color_manual(" ", values=tournament_colors) + my_theme

ggarrange(p3, p1, p2,  p4, nrow=1, ncol=4, common.legend = TRUE, legend="bottom") %>%
grid.arrange(., top = textGrob("Home court advantage: debunked",
                            gp=gpar(fontsize=20, fontfamily="serif")),
             bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
                           just = "left",
                           gp=gpar(fontfamily="serif")))



ggarrange(p3, p1, p2,  p4, nrow=1, ncol=4, common.legend = TRUE, legend="bottom") %>%
grid.arrange(.,
             # top = textGrob("Home court advantage: debunked",
             #                gp=gpar(fontsize=20, fontfamily="serif")),
             bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
                           just = "left",
                           gp=gpar(fontfamily="serif", fontsize = 20))) %>%
  ggsave("plots/home_court.jpg", ., height=5, width=graphic_width_long)

```



```{r}

dplyr::filter(gs_players, ioc == "USA", round < "QF")  %>% nrow()
dplyr::filter(gs_players, ioc == "USA", round < "QF")  %>% pull(name) %>% unique() %>% length()

dplyr::filter(gs_players, ioc == "FRA", round < "QF")  %>% nrow()
dplyr::filter(gs_players, ioc == "FRA", round < "QF")  %>% pull(name) %>% unique() %>% length()

dplyr::filter(gs_players, ioc == "AUS", round < "QF")  %>% nrow()
dplyr::filter(gs_players, ioc == "AUS", round < "QF")  %>% pull(name) %>% unique() %>% length()

dplyr::filter(gs_players, ioc == "GBR", round < "QF")  %>% pull(name) %>% unique() %>% length()
dplyr::filter(gs_players, ioc == "GBR", round < "QF")  %>% nrow()

p1<- ggplot(france_wins, aes(round, win_prop,
                             color=tournament, group=tournament,
                             # alpha = tournament,
                             size = tournament,
                             linetype = tournament)) + 
  # geom_line(size = 3) + 
  # geom_point() +
  labs(title = "French players",
       subtitle = "53 players, n=828",
       x = "", y = " ") + 
  geom_line() + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
# scale_alpha_manual(guide = FALSE,
#                    values = c(our_alpha, 1, our_alpha, our_alpha)) + 
scale_size_manual(guide = FALSE,
                   values = c(1, 3, 1, 1)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(2, 1, 2, 2)) + ylim(c(0, 1))

p2 <- ggplot(us_wins, aes(round, win_prop,
                          color=tournament, group=tournament,
                          # alpha = tournament,
                          size = tournament,
                          linetype=tournament)) + 
  # geom_line() + 
  # geom_point() +
  labs(title = "USA players",
       subtitle = "81 players, n=1046",
              x = "", y = " ") + 
       # x = "", y = "Win proportion") + 
    geom_line() + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
  scale_size_manual(guide = FALSE,
                   values = c(1, 1, 3, 1)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(2, 2, 1, 2)) + ylim(c(0, 1))
# scale_alpha_manual(guide = FALSE,
#                    values = c(our_alpha, our_alpha, 1, our_alpha))

p3 <- ggplot(aus_wins, aes(round, win_prop,
                           color=tournament, group=tournament, # alpha = tournament,
                           size = tournament,
                           linetype = tournament)) + 
  # geom_line() + 
  # geom_point() +
  labs(title = "Aus. players",
       subtitle = "40 players, n=376",
       x = "", y = "Win proportion") + 
         # x = "", y = " ") + 
    geom_line() + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
  scale_size_manual(guide = FALSE,
                   values = c(3, 1, 1, 1)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(1, 2, 2, 2)) + ylim(c(0, 1))
# scale_alpha_manual(guide = FALSE,
#                    values = c(1, our_alpha, our_alpha, our_alpha)) 


p4 <- ggplot(gbr_wins, aes(round, win_prop, color=tournament,
                           group=tournament, fill = tournament,
                           # alpha = tournament,
                           size = tournament,
                           linetype = tournament)) + 
  geom_line() + 
  labs(title = "British players",
       subtitle = "21 players, n=249",
       # x = "", y = "Win proportion") + 
       x = "", y = " ") + 
  scale_color_manual(" ", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme +
  guides(color = guide_legend(override.aes = list(size = 7)))  + 
  scale_size_manual(guide = FALSE,
                   values = c(1, 1, 1, 3)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(2, 2, 2, 1)) + ylim(c(0, 1))

# scale_alpha_manual(guide = FALSE,
#                    values = c(our_alpha, our_alpha, our_alpha, 1))


ggarrange(p3, p1, p2,  p4, nrow=1, ncol=4, common.legend = TRUE, legend="bottom") %>%
grid.arrange(.,
             bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
                           just = "left",
                           gp=gpar(fontfamily="serif", fontsize = 20))) 


ggarrange(p3, p1, p2,  p4, nrow=1, ncol=4, common.legend = TRUE, legend="bottom") %>%
grid.arrange(.,
             # top = textGrob("Home court advantage: debunked",
             #                gp=gpar(fontsize=20, fontfamily="serif")),
             bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
                           just = "left",
                           gp=gpar(fontfamily="serif", fontsize = 20))) %>%
  ggsave("plots/home_court.jpg", ., height=5.5, width=graphic_width_long)


```


```{r}
# home court only with those in all 4

all4 <- 
  gs_players %>% 
  group_by(name) %>% 
  summarize(blah = length(unique(tournament))) %>%
  filter(blah == 4) %>%
  pull(name)


france_wins <- dplyr::filter(gs_players, ioc == "FRA", round < "QF", name %in% all4) %>% 
  dplyr::group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

us_wins <- dplyr::filter(gs_players, ioc == "USA", round < "QF", name %in% all4) %>% 
  dplyr::group_by(tournament, round) %>% 
  dplyr::summarize(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

aus_wins <- filter(gs_players, ioc == "AUS", round < "QF", name %in% all4) %>% 
  group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

gbr_wins <- filter(gs_players, ioc == "GBR", round < "QF", name %in% all4) %>% 
  group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))



p1<- ggplot(france_wins, aes(round, win_prop,
                             color=tournament, group=tournament,
                             # alpha = tournament,
                             size = tournament,
                             linetype = tournament)) + 
  # geom_line(size = 3) + 
  # geom_point() +
  labs(title = "French players",
       x = "", y = " ") + 
  geom_line() + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
# scale_alpha_manual(guide = FALSE,
#                    values = c(our_alpha, 1, our_alpha, our_alpha)) + 
scale_size_manual(guide = FALSE,
                   values = c(1, 3, 1, 1)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(2, 1, 2, 2)) + ylim(c(0, 1))

p2 <- ggplot(us_wins, aes(round, win_prop,
                          color=tournament, group=tournament,
                          # alpha = tournament,
                          size = tournament,
                          linetype=tournament)) + 
  # geom_line() + 
  # geom_point() +
  labs(title = "USA players",
              x = "", y = " ") + 
       # x = "", y = "Win proportion") + 
    geom_line() + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
  scale_size_manual(guide = FALSE,
                   values = c(1, 1, 3, 1)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(2, 2, 1, 2)) + ylim(c(0, 1))
# scale_alpha_manual(guide = FALSE,
#                    values = c(our_alpha, our_alpha, 1, our_alpha))

p3 <- ggplot(aus_wins, aes(round, win_prop,
                           color=tournament, group=tournament, # alpha = tournament,
                           size = tournament,
                           linetype = tournament)) + 
  # geom_line() + 
  # geom_point() +
  labs(title = "Aus. players",
       x = "", y = "Win proportion") + 
         # x = "", y = " ") + 
    geom_line() + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
  scale_size_manual(guide = FALSE,
                   values = c(3, 1, 1, 1)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(1, 2, 2, 2)) + ylim(c(0, 1))
# scale_alpha_manual(guide = FALSE,
#                    values = c(1, our_alpha, our_alpha, our_alpha)) 


p4 <- ggplot(gbr_wins, aes(round, win_prop, color=tournament,
                           group=tournament, fill = tournament,
                           # alpha = tournament,
                           size = tournament,
                           linetype = tournament)) + 
  geom_line() + 
  labs(title = "British players",
       # x = "", y = "Win proportion") + 
       x = "", y = " ") + 
  scale_color_manual(" ", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme +
  guides(color = guide_legend(override.aes = list(size = 7)))  + 
  scale_size_manual(guide = FALSE,
                   values = c(1, 1, 1, 3)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(2, 2, 2, 1)) + ylim(c(0, 1))

# scale_alpha_manual(guide = FALSE,
#                    values = c(our_alpha, our_alpha, our_alpha, 1))


ggarrange(p3, p1, p2,  p4, nrow=1, ncol=4, common.legend = TRUE, legend="bottom") %>%
grid.arrange(.,
             bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
                           just = "left",
                           gp=gpar(fontfamily="serif", fontsize = 20))) 


ggarrange(p3, p1, p2,  p4, nrow=1, ncol=4, common.legend = TRUE, legend="bottom") %>%
grid.arrange(.,
             # top = textGrob("Only those who made all 4",
             #                gp=gpar(fontsize=20, fontfamily="serif")),
             bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
                           just = "left",
                           gp=gpar(fontfamily="serif", fontsize = 20))) %>%
  ggsave("plots/home_court_all4.jpg", ., height=5, width=graphic_width_long)




```



## Spaniards on clay

```{r}

spain_wins <- filter(gs_players, ioc == "ESP", round < "QF") %>% 
  group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()),
            avg_ranking = mean(rank),
            rank_se = sd(rank)/sqrt(n()))

prop.table(with(filter(gs_players, ioc == "ESP", round == "R128"),
                table(did_win, tournament)), 2)

with(filter(gs_players, ioc == "ESP", round == "R128"),
                table(did_win, tournament))

with(filter(gs_players, ioc == "ESP", round == "R128"),
     table(did_win, tournament)) %>%
  chisq.test(correct = TRUE)

```



```{r, fig.height=3.8, fig.width=8, out.width="80%", fig.align='center', fig.cap = "\\label{fig:spain-clay}"}

# my_theme <-  theme_bw() + # White background, black and white theme
#   theme(axis.text = element_text(size = 24),
#         text = element_text(size = 28,
#         family="serif"),
#         plot.title = element_text(hjust = 0.5, size=34))

p1 <- ggplot(spain_wins, aes(round, win_prop, color=tournament, group=tournament)) + 
  labs(title = "Win proportion among Spaniards",
       # caption = "Note: we only look at the first 4 rounds due to decreasing sample size",
       x = "", y = "Win proportion") + 
    geom_line(size=3) + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme  

p2 <- ggplot(spain_wins, aes(round, avg_ranking, color=tournament, group=tournament, fill = tournament)) + 
  geom_line(size=3) + 
  labs(title = "Average ranking among Spaniards",
       x = " ",
       y = "Average rank") + 
  scale_color_manual(" ", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme +
  guides(color = guide_legend(override.aes = list(size = 7))) 


ggarrange( p1, p2, nrow=1, ncol=2, common.legend = TRUE, legend="bottom") %>%
grid.arrange(top = textGrob("Spaniards perform better on Clay: confirmed?",
                            gp=gpar(fontsize=20, fontfamily="serif")),
             bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
                           # x = 0,
                           # y = 0.5,
                           just = "left",
                           gp=gpar(fontfamily="serif")))

ggarrange( p1, p2, nrow=1, ncol=2, common.legend = TRUE, legend="bottom") %>%
  ggsave("plots/spainards.jpg", ., height=6, width=graphic_width_long)


```


# Unforced errors and aces


```{r, out.width="70%", fig.width=7, fig.height=3.5, fig.align='center'}

# my_theme <-  theme_bw() + # White background, black and white theme
#   theme(axis.text = element_text(size = 24),
#         text = element_text(size = 28,
#         family="serif"),
#         plot.title = element_text(hjust = 0.5, size=34))

# ggplot(gs_partial, aes(w_n_ue + l_n_ue, w_n_aces + l_n_aces,
#                            label = tournament, color=tournament)) + 
#   geom_jitter(size=2) +
#   labs( title = "Distribution of errors and aces differ by tournament",
#         x = "Total unforced errors", y = "Total aces") +
#   my_theme + scale_color_manual("Tournament",
#                                 values = tournament_colors,
#                                 labels = c("Australian Open\n(Plexicushion)\n",
#                                            "French Open\n(Clay)\n",
#                                            "US Open\n(DecoTurf)\n",
#                                            "Wimbledon\n(Grass)\n")) + 
#   geom_density_2d()

ggplot(gs_partial, aes(w_n_ue + l_n_ue, w_n_aces + l_n_aces,
                           label = tournament, color=tournament)) + 
  geom_jitter(size=2) +
  labs( title = "Distribution of errors and aces differ by tournament",
        x = "Total unforced errors", y = "Total aces") +
  my_theme + scale_color_manual("Tournament",
                                values = tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)\n",
                                           "French Open\n(Clay)\n",
                                           "US Open\n(DecoTurf)\n",
                                           "Wimbledon\n(Grass)\n")) +
  stat_ellipse(type="t", size = 2) +
  guides(color = guide_legend(override.aes = list(size = 7, shape=15))) 

ggsave("plots/errors_aces2.jpg", height = 6, width = graphic_width_short)

```



## Tall players and aces

```{r, fig.width=10, fig.height=4.8, fig.align='center'}

# my_theme <-  theme_bw() + # White background, black and white theme
#   theme(axis.text = element_text(size = 24),
#         text = element_text(size = 28,
#         family="serif"),
#         plot.title = element_text(hjust = 0.5, size=34))

# my_theme <-  theme_bw() + # White background, black and white theme
#   theme(axis.text = element_text(size = 26),
#         text = element_text(size = 30,
#         family="serif"),
#         plot.title = element_text(hjust = 0.5, size=36))

set.seed(8)

atp_servers <- c("Ivo Karlovic", "John Isner", "Rafael Nadal",
                 "Roger Federer", "Andy Murray")
atp_servers <- sapply(atp_servers,
                      function(x) return(sample(which(gs_players$name == x), 2))) %>%
  as.numeric() %>% gs_players[., ]

wta_servers <- c("Karolina Pliskova", "Caroline Wozniacki",
                 "Venus Williams", "Serena Williams", "Madison Keys")
wta_servers <- sapply(wta_servers,
                      function(x) return(sample(which(gs_players$name == x), 2))) %>%
  as.numeric() %>% gs_players[., ]


p_atp <- gs_players %>% filter(league == "ATP") %>%
ggplot( aes(log(ht+1), log(ace+1))) + 
  geom_jitter(aes(color = tournament), size=1.5) + 
  # scale_color_manual(" ", values = tournament_colors) + 
  geom_smooth( method = "lm", color="black") + 
  geom_label_repel(data=atp_servers,
            aes(log(ht+1), log(ace+1), label=name),
            alpha=.8, seed=1234, show.legend=FALSE, size = 8) + 
  geom_label_repel(data=atp_servers,
            aes(log(ht+1), log(ace+1), label = name),
            seed=1234, fill=NA, show.legend=FALSE, size = 8) +
  labs(x = "log(height + 1)", title = "ATP") +
  my_theme + scale_color_manual("Tournament",
                                values = tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)\n",
                                           "French Open\n(Clay)\n",
                                           "US Open\n(DecoTurf)\n",
                                           "Wimbledon\n(Grass)\n")) +
  guides(color = guide_legend(override.aes = list(size = 7, shape=15)))

p_wta <- gs_players %>% filter(league == "WTA") %>%
ggplot(aes(log(ht+1), log(ace+1))) + 
  geom_jitter(aes(color = tournament)) + 
  # scale_color_manual(" ", values = tournament_colors) + 
  geom_smooth(method = "lm", color="black") + 
  geom_label_repel(data=wta_servers,
            aes(log(ht+1), log(ace+1), label=name),
            alpha=.8, seed=1234, show.legend=FALSE, size = 8) + 
  geom_label_repel(data=wta_servers,
            aes( log(ht+1), log(ace+1), label=name),
            seed=1234, fill=NA, show.legend=FALSE, size = 8) +
  labs(x = "log(height + 1)", title = "WTA")+
  my_theme + scale_color_manual("Tournament",
                                values = tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)\n",
                                           "French Open\n(Clay)\n",
                                           "US Open\n(DecoTurf)\n",
                                           "Wimbledon\n(Grass)\n")) +
  guides(color = guide_legend(override.aes = list(size = 7, shape=15))) 

# grid.arrange(p_atp, p_wta, nrow=1, widths=c(.4, .6),
#              top = textGrob("Taller players are better servers: confirmed",
#                             gp=gpar(fontsize=20, fontfamily="serif")))

ggarrange(p_atp, p_wta, common.legend = TRUE, legend="bottom") 
# %>%  grid.arrange(top = textGrob("Taller players are better servers: confirmed",
#                             gp=gpar(fontsize=20, fontfamily="serif")))

# ggsave("plots/aces.jpg", height=7, width=16)
ggsave("plots/aces2.jpg", height=7, width=graphic_width_long)

```




```{r, fig.width=6, fig.height=6, fig.align='center'}


# p_atp <- gs_players %>% filter(league == "ATP") %>%
# ggplot( aes(log(ht+1), log(ace+1))) + 
#   geom_jitter(aes(color = tournament)) + 
#   scale_color_manual(guide=FALSE, values = tournament_colors) + 
#   geom_smooth( method = "lm", se=FALSE, color="black") + 
#   geom_label_repel(data=atp_servers,
#             aes(log(ht+1), log(ace+1), label=name),
#             alpha=.6, seed=1234, show.legend=FALSE) + 
#   geom_label_repel(data=atp_servers,
#             aes(log(ht+1), log(ace+1), label = name),
#             seed=1234, fill=NA, show.legend=FALSE) +
#   labs(x = "log(height + 1)", title = "ATP") +
#   my_theme
# 
# # subset(filter(gs_players, league == "WTA"),
# #                                (log(ht+1) > 5.22 & log(ace+1) > 2.6) |
# #                                 (log(ht+1) > 5.225 & log(ace+1) < .5) | 
# #                                 (log(ht+1) < 5.13 & log(ace+1) > 2.1) | 
# #                                 (log(ht+1) < 5.09 & log(ace+1) > 1.5) |
# #                                  (log(ace + 1) > 2.82))
# p_wta <- gs_players %>% filter(league == "WTA") %>%
# ggplot(aes(log(ht+1), log(ace+1))) + 
#   geom_jitter(aes(color = tournament)) + 
#   scale_color_manual("Tournament", values = tournament_colors) + 
#   geom_smooth(aes(color = tournament), method = "lm", se=FALSE) + 
#   geom_label_repel(data=wta_servers,
#             aes(log(ht+1), log(ace+1), label=name),
#             alpha=.6, seed=1234, show.legend=FALSE) + 
#   geom_label_repel(data=wta_servers,
#             aes(log(ht+1), log(ace+1), label=name),
#             seed=1234, fill=NA, show.legend=FALSE) +
#   labs(x = "log(height + 1)", title = "WTA")+
#   my_theme + theme(legend.position="bottom")
# 
# 
# grid.arrange(p_atp, p_wta, nrow=2, heights = c(.46, .54),
#              top = textGrob("Taller players are better servers: confirmed",
#                             gp=gpar(fontsize=20, fontfamily="serif")))

```



### Linear regression for other outcomes

```{r, eval = FALSE}
gs_partial_players$atp = gs_partial_players$Tour == "atp"
gs_partial_players$year_fac = as.factor(gs_partial_players$year)
gs_partial_players$late_round = gs_partial_players$round >= "R16"
gs_partial_players$seeded = gs_partial_players$rank <= 32
gs_partial_players$opponent_seeded = gs_partial_players$opponent_rank <= 32
n_aces_mod = lmer(n_aces ~ late_round + log(rank) + log(opponent_rank) + year_fac + atp + (0 + tournament |name), data = gs_partial_players)
n_winners_mod = lmer(n_winners ~ late_round + log(rank) + log(opponent_rank) + year_fac + atp + (0 + tournament |name), data = gs_partial_players)
n_net_mod = lmer(n_netpt_w ~ late_round + log(rank) + log(opponent_rank) + year_fac + atp + (0 + tournament |name), data = gs_partial_players)
n_ue_mod = lmer(n_ue ~ late_round + log(rank) + log(opponent_rank) + year_fac + atp + (0 + tournament |name), data = gs_partial_players)
```

```{r}
load("../../data/n_aces_mod.rda")
load("../../data/n_net_mod.rda")
load("../../data/n_ue_mod.rda")
load("../../data/n_winners_mod.rda")
```

```{r, fig.height = 3.3, fig.width=10,  fig.cap = "\\label{fig:mixed-mods-stats}Estimated player-level effects for Williams, Federer and Nadal when modeling aces, net winners, and unforced errors."}

# my_theme <-  theme_bw() + # White background, black and white theme
#   theme(axis.text = element_text(size = 20),
#         text = element_text(size = 24,
#         family="serif"),
#         plot.title = element_text(hjust = 0.5, size=26))

aces_ranef = as.data.frame(ranef(n_aces_mod, condVar = TRUE)) %>%
  mutate(tournament = gsub("tournament", "", term)) %>%
  filter(., grp == "Serena Williams" | grp == "Rafael Nadal" | grp == "Roger Federer") %>%
  ggplot(., aes(x = as.character(grp), y = condval,
                ymin = condval- 2*condsd, ymax = condval + 2*condsd, col = tournament)) +
  geom_errorbar(height = .5, position = position_dodge(width=.5), size =2) +
  ylab("Coefficient\n") + 
  xlab("") +
  ggtitle("Y = aces") + 
  scale_color_manual("", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) +
  my_theme +
  coord_flip() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  geom_hline(yintercept = 0, color = "grey") +
  guides(color = guide_legend(override.aes = list(size = 7))) 

# winners_ranef = as.data.frame(ranef(n_winners_mod, condVar = TRUE)) %>%
#   mutate(tournament = gsub("tournament", "", term)) %>%
#   filter(., grp == "Serena Williams" | grp == "Rafael Nadal" | grp == "Roger Federer") %>%
#   ggplot(., aes(x = as.character(grp), y = condval, ymin = condval- 2*condsd, ymax = condval + 2*condsd, col = tournament)) +
#   geom_errorbar(height = .5, position = position_dodge()) +
#   ylab("Coefficient\n") + 
#   xlab("") +
#   ggtitle("Winners") + 
#   scale_color_manual("", values=tournament_colors,
#                                 labels = c("Australian Open\n(Plexicushion)",
#                                            "French Open\n(Clay)",
#                                            "US Open\n(DecoTurf)",
#                                            "Wimbledon\n(Grass)")) +
#   my_theme  +
#   coord_flip() +
#   theme(panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         axis.text.y = element_blank()) +
#   geom_hline(yintercept = 0, color = "grey")


nets_ranef = as.data.frame(ranef(n_net_mod, condVar = TRUE)) %>%
  mutate(tournament = gsub("tournament", "", term)) %>%
  filter(., grp == "Serena Williams" | grp == "Rafael Nadal" | grp == "Roger Federer") %>%
  ggplot(., aes(x = as.character(grp), y = condval, ymin = condval- 2*condsd, ymax = condval + 2*condsd, col = tournament)) +
  geom_errorbar(height = .5, position = position_dodge(width=.5), size =2) +
  ylab("Coefficient\n") + 
  xlab("") +
  ggtitle("Y = points won at net") + 
  scale_color_manual("", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) +
  my_theme  +
  coord_flip() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank()) +
  geom_hline(yintercept = 0, color = "grey") +
  guides(color = guide_legend(override.aes = list(size = 7))) 


ue_ranef = as.data.frame(ranef(n_ue_mod, condVar = TRUE)) %>%
  mutate(tournament = gsub("tournament", "", term)) %>%
  filter(., grp == "Serena Williams" | grp == "Rafael Nadal" | grp == "Roger Federer") %>%
  ggplot(., aes(x = as.character(grp),
                y = condval,
                ymin = condval- 2*condsd,
                ymax = condval + 2*condsd, col = tournament)) +
  geom_errorbar(height = .5, position = position_dodge(width=.5), size =2) +
  ylab("Coefficient\n") + 
  xlab("") +
  ggtitle("Y = unforced errors") + 
  scale_color_manual("", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) +
  my_theme  +
  coord_flip() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank()) +
  geom_hline(yintercept = 0, color = "grey") +
  guides(color = guide_legend(override.aes = list(size = 7))) 


#grid.arrange(aces_ranef, nets_ranef, ue_ranef, nrow = 1, widths = c(.38, .22, .45))

ggarrange(aces_ranef, nets_ranef, ue_ranef, nrow=1, ncol=3,
          common.legend = TRUE, legend="bottom", widths = c(.42, .29, .29)) 

ggarrange(aces_ranef, nets_ranef, ue_ranef, nrow=1, ncol=3,
          common.legend = TRUE, legend="bottom", widths = c(.42, .29, .29)) %>%
ggsave("plots/player_effects.jpg", ., height=6, width = graphic_width_long)

```


## player effects


```{r nadal-model}

step_model_n <- courtsports:::model_individual(player_name = "Rafael Nadal", data = gs_partial_players)

std_res_n <- rstandard(step_model_n)

gn <- ggplot(lm(step_model_n$formula, data = step_model_n$data)) + geom_hline(yintercept = 0, col = "red") +
  geom_point(aes(x=.fitted, y = .stdresid)) + my_theme + ylim(-3, 3) +
  labs(title = "Nadal",
       x = "Predicted Percent of Points Won", y = "Standardized Residuals")


coefs_n <- coefficients(step_model_n)
cov_n <- vcov(step_model_n)

 ## NADAL COEF SIZE
 
df_n <- data.frame(coeff = names(step_model_n$coeff), ave = step_model_n$coeff, sd = sqrt(diag(vcov(step_model_n))))
df_n$player <- "Nadal"
```

```{r federer-model}

step_model_f <- courtsports:::model_individual(player_name = "Roger Federer", data = gs_partial_players, ref = "Wimbledon")

std_res_f <- rstandard(step_model_f)

gf <- ggplot(lm(step_model_f$formula, data = step_model_f$data)) + geom_hline(yintercept = 0, col = "red") +
  geom_point(aes(x=.fitted, y = .stdresid)) + my_theme + ylim(-3, 3) +
  labs(title = "Federer",
       x = "Predicted Percent of Points Won", y = "Standardized Residuals")


coefs_f <- coefficients(step_model_f)
cov_f <- vcov(step_model_f)
 
df_f <- data.frame(coeff = names(step_model_f$coeff), ave = step_model_f$coeff, sd = sqrt(diag(vcov(step_model_f))))
df_f$player <- "Federer"
```





```{r williams-model}

step_model_w <- courtsports:::model_individual(player_name = "Serena Williams", data = gs_partial_players,
                                 start_lower = TRUE, ref = "Australian Open")

std_res_w <- rstandard(step_model_w)

gw <- ggplot(lm(step_model_w$formula, data = step_model_w$data)) + geom_hline(yintercept = 0, col = "red") +
  geom_point(aes(x=.fitted, y = .stdresid)) + my_theme + ylim(-3, 3) +
  labs(title = "Williams",
       x = "Predicted Percent of Points Won", y = "Standardized Residuals")

cov_w <- vcov(step_model_w)
coefs_w <- coefficients(step_model_w)

 ## WilliamsCOEF SIZE
 
df_w <- data.frame(coeff = names(step_model_w$coeff), ave = step_model_w$coeff, sd = sqrt(diag(vcov(step_model_w))))
df_w$player <- "Williams"
```


```{r plot-individual-effects}
df <- rbind(df_n, df_w, df_f)
keep_coefs <- which(df$coeff %in% c("(Intercept)", "opponent_rank",
                                    "pct_ace", "pct_bp", "pct_netpt",
                                    "ave_serve_speed", "wue_ratio"))
df <- df[keep_coefs,]
ggplot(df, aes(x = coeff, y = ave, col = player)) +
  geom_errorbar(aes(ymin = ave - 2 *sd, ymax = ave + 2 * sd),
                position = "dodge", width = .3, size = 2) + 
   my_theme +
  # coord_flip() +
  theme(axis.text.x=element_text(angle = 30, hjust = 1)) +
  geom_hline(yintercept = 0, color = "grey") + 
  ggtitle("Fixed effects") +
  scale_color_brewer("", palette = "Dark2") +
  theme(legend.position = "bottom") +
  xlab("") + 
  ylab("Coefficient") +
  scale_x_discrete(labels = c("Intercept", "Opp. Rank", "% Aces",
                              "% Break Points Won", "% Net Points Won",
                              "Ave. Serve Speed", "Winner:UE"))  +
  guides(color = guide_legend(override.aes = list(size = 7)))  +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
  
ggsave("plots/ref-courts-eff.jpg", height=6, width = graphic_width_short)

  #ggsave("~/Documents/ref-courts-eff.pdf", width = 8, height = 6, height=6, width = graphic_width_long)
```
  
  
# amanda model fitting
  



```{r}
win_colors <- c("#336699", "#339966")

# with yellow for us
# tournament_colors <- c("#0297DB", "#b06835", "#ffe500", "#54008b")

model_names = c("nocourt_logistic", "base_logistic", "country_logistic", "ind_logistic", 
                "ind_logistic_noioc", "ind_int_logistic", "ind_year_logistic")

model.sums = data.frame(model = model_names, aic = rep(NA, length(model_names)), edf = rep(NA,length(model_names)))
model.ests = data.frame()
ran.effects = data.frame()
for(mod in 1:nrow(model.sums)){
  name = model_names[mod]
  model.sums$aic[mod] = extractAIC(get(name))[2]
  model.sums$edf[mod] = extractAIC(get(name))[1]
  betas = tidy(get(name))
  betas$model = name
  if("group" %in% colnames(betas)){
    model.ests = rbind(model.ests, filter(betas, group == "fixed") %>%
                         dplyr::select(., -c("group")))
  }
  else model.ests = rbind(model.ests, betas)
}

model.sums$name = c("no_court", "no_random_ef", "country_ef", "ind_ef", "ind_no_ioc", "ind_intercept", "ind_year_ef")
model.sums$fixed = c("No country, no tournament",
                     "all",
                     "no country, no tournament",
                     "no tournament",
                     "no country, no tournament",
                     "no country",
                     "no country, no year")
model.sums$random = c("none",
                      "none",
                      "tournament (by country)",
                      "tournament (by individual)",
                      "tournament (by individual)",
                      "intercept (by individual)",
                      "year (by individual)")

fixed.effects.plot = model.ests %>%
  filter(., !grepl("ioc", term)) %>% 
  filter(., model == 'ind_logistic_noioc') %>%
  ggplot(., aes(x = term, y = estimate, col = model, ymin = estimate - 2*std.error, ymax = estimate + 2*std.error)) +
  geom_errorbar(width = .7, position = position_dodge(), size = 1.5) +
  my_theme +
  # coord_flip() +
  theme(axis.text.x=element_text(angle = 35, hjust = 1)) +
  ggtitle("Fixed effects") +
  scale_color_brewer("",palette = "Dark2") +
  theme(legend.position = "none") + 
  xlab("") +
  ylab("Coefficient") +
  scale_x_discrete("", breaks = waiver(), labels = c("Intercept", "ATP", "Late round", "Op Rank (log)", "Rank (log)", "2014", "2015", "2016", "2017"))+
  guides(col = guide_legend(nrow=2)) +
  geom_hline(yintercept = 0, color = "grey") + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

ran_tourn = rbind(ranef(ind_logistic)$name_int, ranef(ind_logistic_noioc)$name_int)
ran_tourn$model = c(rep("ind_logistic", nrow(ranef(ind_logistic)$name_int)), rep("ind_logistic_noioc", nrow(ranef(ind_logistic)$name_int)))

gs_players$name_int = as.integer(as.factor(gs_players$name))
name_lookup = unique(cbind(gs_players$name, gs_players$name_int))
name_lookup = name_lookup[order(as.integer(name_lookup[,2])),]

top_three_ranef = as.data.frame(ranef(ind_logistic_noioc, condVar = TRUE)) %>%
  mutate(tournament = gsub("tournament", "", term)) %>%
  mutate(name = name_lookup[,1][as.integer(grp)]) %>% 
  filter(., name == "Serena Williams" | name == "Rafael Nadal" | name == "Roger Federer") %>%
  ggplot(., aes(x = name, y = condval, ymin = condval- 2*condsd, ymax = condval + 2*condsd, color = tournament)) +
  geom_errorbar(width = .5, position = "dodge",size = 1.5) + 
  xlab("") + 
  ylab("Coefficient") + 
  scale_color_manual("", values=tournament_colors) +
  my_theme +
  coord_flip() +
  ggtitle("Random Effects") +
  theme(legend.position = "bottom") + 
  guides(col = guide_legend(nrow=2,
                            override.aes = list(size = 7))) +
  geom_hline(yintercept = 0, color = "grey") + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

grid.arrange(fixed.effects.plot, top_three_ranef, nrow = 1, widths = c(.45, .55) #,
             # top = textGrob("Parameter estimates from logistic model",
             #                gp=gpar(fontsize=20, fontfamily="serif"))
             ) %>%
ggsave("plots/logistic-parameter-effects.jpg",., height=7, width=graphic_width_long)

```


```{r}

fixed.effects.plot.linear <- tidy(n_aces_mod) %>%
  filter(., group == 'fixed') %>%
  mutate(., model = "Aces") %>%
  bind_rows(
    tidy(n_ue_mod) %>%
      filter(., group == 'fixed') %>%
      mutate(., model = "UE")
  ) %>%
  bind_rows(
    tidy(n_net_mod) %>%
      filter(., group == 'fixed') %>%
      mutate(., model = "Net")
  ) %>%
  ggplot(., aes(x = term, y = estimate, 
                ymin = estimate - 2*std.error, 
                ymax = estimate + 2*std.error,
                col = model,
                group = model)) + 
  geom_errorbar(width = .7, position = position_dodge(), size = 1.5) +
  my_theme +
  # coord_flip() +
  theme(axis.text.x=element_text(angle = 35, hjust = 1)) +
  ggtitle("Fixed effects") +
  scale_color_brewer("",palette = "Dark2") +
  theme(legend.position = "bottom") + 
  xlab("") +
  ylab("Coefficient") +
  scale_x_discrete("", 
                   breaks = waiver(), 
                   labels = c("Intercept", "ATP", "Late round", "Op Rank (log)",
                              "Rank (log)", "2014", "2015", "2016", "2017"))  +
  guides(color = guide_legend(override.aes = list(size = 7)))  +
  geom_hline(yintercept = 0, color = "grey") + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
  
ggsave("plots/linear-fixed-effects.jpg", fixed.effects.plot.linear,
       height=6, width = graphic_width_short)


```




```{r}

fixed.effects.plot.allmods = model.ests %>%
  filter(., !grepl("ioc", term)) %>% 
  ggplot(., aes(x = term, y = estimate, col = model, ymin = estimate - 2*std.error, ymax = estimate + 2*std.error)) +
  geom_errorbar(width = .7, position = position_dodge(), size = 1.5) +
  my_theme +
  # coord_flip() +
  theme(axis.text.x=element_text(angle = 35, hjust = 1, size = 10)) +
  ggtitle("Fixed effects") +
  scale_color_brewer("",palette = "Dark2") +
  theme(legend.position = "none") + 
  xlab("") +
  ylab("Estimate") +
  scale_x_discrete("", 
                   breaks = waiver(), 
                   labels = c("Intercept", "ATP", "Late round", "Op Rank (log)", "Rank (log)", "French", "US", "Wimbledon", "2014", "2015", "2016", "2017")) +
  guides(col = guide_legend(nrow=2))

aces_ranef = as.data.frame(ranef(n_aces_mod, condVar = TRUE)) %>%
  mutate(tournament = gsub("tournament", "", term)) %>%
  filter(., grp == "Serena Williams" | grp == "Rafael Nadal" | grp == "Roger Federer") %>%
  ggplot(., aes(x = as.character(grp), y = condval, ymin = condval- 2*condsd, ymax = condval + 2*condsd, col = tournament)) +
  geom_errorbar(height = .5, position = position_dodge(), size = 1.5) +
  ylab("Estimate") + 
  xlab("") +
  ggtitle("Aces") + 
  scale_color_manual("", values=tournament_colors) +
  my_theme +
  coord_flip() +
  theme(legend.position = "none")

nets_ranef = as.data.frame(ranef(n_net_mod, condVar = TRUE)) %>%
  mutate(tournament = gsub("tournament", "", term)) %>%
  filter(., grp == "Serena Williams" | grp == "Rafael Nadal" | grp == "Roger Federer") %>%
  ggplot(., aes(x = as.character(grp), y = condval, ymin = condval- 2*condsd, ymax = condval + 2*condsd, col = tournament)) +
  geom_errorbar(height = .5, position = position_dodge(), size = 1.5) +
  ylab("Estimate") + 
  xlab("") +
  ggtitle("Net Wins") + 
  scale_color_manual("", values=tournament_colors) +
  my_theme +
  theme(axis.text.y = element_blank()) +
  coord_flip() # +
# theme(legend.position = "none")

ue_ranef = as.data.frame(ranef(n_ue_mod, condVar = TRUE)) %>%
  mutate(tournament = gsub("tournament", "", term)) %>%
  filter(., grp == "Serena Williams" | grp == "Rafael Nadal" | grp == "Roger Federer") %>%
  ggplot(., aes(x = as.character(grp), y = condval, ymin = condval- 2*condsd, ymax = condval + 2*condsd, col = tournament)) +
  geom_errorbar(height = .5, position = position_dodge(), size = 1.5) +
  ylab("Estimate") + 
  xlab("") +
  ggtitle("Unforced Errors") + 
  scale_color_manual("", values=tournament_colors) +
  my_theme +
  theme(axis.text.y = element_blank()) +
  coord_flip()# + 
#theme(legend.text=element_text(size=10))

#grid.arrange(aces_ranef, nets_ranef, ue_ranef, nrow = 1, widths = c(.38, .22, .45))

```



# correlation plots

```{r}
win_colors <- c("#336699", "#339966")

mat <- matrix(c(1, 0, .94, .93,
         0, 1, -.05, -.36,
         .94, -.05, 1, .88,
         .93, -.36, .88, 1), byrow = TRUE, nrow = 4)
colnames(mat) <- c("Aus. Open", "French Open", "US Open", "Wimbledon")
rownames(mat) <- c("Aus. Open", "French Open", "US Open", "Wimbledon")
#
df <- melt(mat)
#
ggplot(df, aes(x = Var1, y = Var2, fill = value)) + geom_tile() +
     geom_tile(color = "white")+
    scale_fill_gradient2(low = win_colors[2], high = win_colors[1], mid = "white", 
                         midpoint = 0, limit = c(-1,1), 
                         space = "Lab", name="Correlation") + 
                         # labels = c("-1.0", "-0.5", "  0.0", "  0.5", "  1.0")) + 
  labs(x = "", y = "",
       title = "Correlation matrix for random effects")  +
  my_theme

ggsave("plots/correlation.jpg", 
       height=6, width = graphic_width_short)


```

  
  
# extras
  
  
  
```{r, fig.height=3.5, fig.width=10, fig.align='center', eval=FALSE}


ggplot(gs_players, aes(round, pointswon/(rank - opponent_rank), group=tournament)) + 
  geom_line()

ggplot(gs_players, aes(round, pointswon/(rank - opponent_rank), group=tournament)) + 
  geom_point()

filter(gs_players, ioc == "FRA", round < "QF", league == "WTA") %>%
ggplot( aes(x = ( opponent_rank - rank), y = (pointswon - (total_points - pointswon)),
            color = tournament)) + 
  geom_point() +
  geom_smooth(method = "lm", se=FALSE)

p1 <- filter(gs_players, ioc == "FRA", round < "QF", league == "WTA") %>%
ggplot( aes(x = ( opponent_rank - rank), y = did_win,
            color = tournament)) + 
  geom_point() +
  geom_smooth(method = "lm", se=FALSE) +
  labs(title = "French players",
      y = "Win proportion",
      x = " ") + 
  scale_color_manual(" ", values=tournament_colors) + my_theme +
  xlim(c(-1300, 800))  + scale_y_continuous(breaks = c(0, 1),
                                            labels =c("No", "Yes"),
                                            limits = c(0, 1))

p2 <-filter(gs_players, ioc == "AUS", round < "QF", league == "WTA") %>%
ggplot( aes(x = ( opponent_rank - rank), y = did_win,
            color = tournament)) + 
  geom_point() +
  geom_smooth(method = "lm", se=FALSE) +
  labs(title = "Australian players",
      y = "Win proportion",
      x = " ") + 
  scale_color_manual(" ", values=tournament_colors) + my_theme +
  xlim(c(-1300, 800))  + scale_y_continuous(breaks = c(0, 1),
                                            labels =c("No", "Yes"),
                                            limits = c(0, 1))

p3 <-filter(gs_players, ioc == "USA", round < "QF", league == "WTA") %>%
ggplot( aes(x = ( opponent_rank - rank), y = did_win,
            color = tournament)) + 
  geom_point() +
  geom_smooth(method = "lm", se=FALSE) +
  labs(title = "American players",
      y = "Win proportion") + 
  scale_color_manual(" ", values=tournament_colors) + my_theme +
  xlim(c(-1300, 800))  + scale_y_continuous(breaks = c(0, 1),
                                            labels =c("No", "Yes"),
                                            limits = c(0, 1))

p4 <-filter(gs_players, ioc == "GBR", round < "QF", league == "WTA") %>%
ggplot( aes(x = ( opponent_rank - rank), y = did_win,
            color = tournament)) + 
  geom_point() +
  geom_smooth(method = "lm", se=FALSE) +
  labs(title = "English players",
      y = "Win proportion") + 
  scale_color_manual(" ", values=tournament_colors) + my_theme +
  xlim(c(-1300, 800))  + scale_y_continuous(breaks = c(0, 1),
                                            labels =c("No", "Yes"),
                                            limits = c(0, 1))

# grid.arrange(p1, p2, p3, p4, nrow=2)


ggarrange(p1, p2, p3, p4, nrow=2, ncol=2, common.legend = TRUE, legend="bottom") %>%
grid.arrange(., top = textGrob("WTA",
                            gp=gpar(fontsize=30, fontfamily="serif")),
             bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
                           just = "left",
                           gp=gpar(fontfamily="serif"))) %>%
ggsave("plots/wta.jpg", ., width = 10, height = 8)


p1 <- filter(gs_players, ioc == "FRA", round < "QF", league == "ATP") %>%
ggplot( aes(x = ( opponent_rank - rank), y = did_win,
            color = tournament)) + 
  geom_point() +
  geom_smooth(method = "lm", se=FALSE) +
  labs(title = "French players",
      y = "Win proportion",
      x = " ") + 
  scale_color_manual(" ", values=tournament_colors) + my_theme +
  xlim(c(-1500, 1500))  + scale_y_continuous(breaks = c(0, 1),
                                            labels =c("No", "Yes"),
                                            limits = c(0, 1))

p2 <-filter(gs_players, ioc == "AUS", round < "QF", league == "ATP") %>%
ggplot( aes(x = ( opponent_rank - rank), y = did_win,
            color = tournament)) + 
  geom_point() +
  geom_smooth(method = "lm", se=FALSE) +
  labs(title = "Australian players",
      y = "Win proportion",
      x = " ") + 
  scale_color_manual(" ", values=tournament_colors) + my_theme +
  xlim(c(-1500, 1500))  + scale_y_continuous(breaks = c(0, 1),
                                            labels =c("No", "Yes"),
                                            limits = c(0, 1))

p3 <-filter(gs_players, ioc == "USA", round < "QF", league == "ATP") %>%
ggplot( aes(x = ( opponent_rank - rank), y = did_win,
            color = tournament)) + 
  geom_point() +
  geom_smooth(method = "lm", se=FALSE) +
  labs(title = "American players",
      y = "Win proportion") + 
  scale_color_manual(" ", values=tournament_colors) + my_theme +
  xlim(c(-1500, 1500))  + scale_y_continuous(breaks = c(0, 1),
                                            labels =c("No", "Yes"),
                                            limits = c(0, 1))

p4 <-filter(gs_players, ioc == "GBR", round < "QF", league == "ATP") %>%
ggplot( aes(x = ( opponent_rank - rank), y = did_win,
            color = tournament)) + 
  geom_point() +
  geom_smooth(method = "lm", se=FALSE) +
  labs(title = "English players",
      y = "Win proportion") + 
  scale_color_manual(" ", values=tournament_colors) + my_theme +
  xlim(c(-1500, 1500))  + scale_y_continuous(breaks = c(0, 1),
                                            labels =c("No", "Yes"),
                                            limits = c(0, 1))



ggarrange(p1, p2, p3, p4, nrow=2, ncol=2, common.legend = TRUE, legend="bottom") %>%
grid.arrange(., top = textGrob("ATP",
                            gp=gpar(fontsize=30, fontfamily="serif")),
             bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
                           just = "left",
                           gp=gpar(fontfamily="serif"))) %>%
ggsave("plots/atp.jpg", ., width = 10, height = 8)

```
