---
title: "Opening up the court (surface) in tennis grand slams"
date: ' '
output:
  pdf_document:
    toc:  true
header-includes:
  - \usepackage{hyperref}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message = FALSE)

# devtools::install_github("skoval/deuce")
library(deuce)
library(dplyr)
library(tidyr)
library(ggplot2)
library(forcats)
library(stringr)
library(knitr)
library(kableExtra)
library(gridExtra)
library(grid)
library(MASS)
library(ggrepel)
library(broom)
library(lme4)
library(cowplot)
library(ggpubr)
library(reshape2)
# devtools::install_github("shannong19/courtsports")
library(courtsports)
```

```{r graphing-parameters, include = FALSE}
my_theme <-  theme_bw() + # White background, black and white theme
  theme(axis.text = element_text(size = 24),
        text = element_text(size = 28,
        family="serif"),
        plot.title = element_text(hjust = 0.5, size=34),
        plot.subtitle = element_text(hjust = 0.5))

league_colors <- c("#0C2340", "#902BA3")
win_colors <- c("#336699", "#339966")
# with yellow for us
tournament_colors <- c("#0297DB", "#b06835", "#ffe500", "#54008b")

graphic_width_long <- 16
graphic_width_short <- 12

# SHOULD WE WRITE/SAVE THE GRAPHICS LOCALLY??
save_graph <- FALSE
```


```{r data-cleaning, include = FALSE}
data(gs)
data(gs_players)
data(gs_partial)
data(gs_partial_players)
```


## Linear regression for other outcomes

```{r}
load("../../data/n_aces_mod.rda")
load("../../data/n_net_mod.rda")
load("../../data/n_ue_mod.rda")
load("../../data/n_winners_mod.rda")
```

### Player effects

```{r, fig.height = 6, fig.width=16}
aces_ranef = as.data.frame(ranef(n_aces_mod, condVar = TRUE)) %>%
  mutate(tournament = gsub("tournament", "", term)) %>%
  filter(., grp == "Serena Williams" | grp == "Rafael Nadal" | grp == "Roger Federer") %>%
  ggplot(., aes(x = as.character(grp), y = condval,
                ymin = condval- 2*condsd, ymax = condval + 2*condsd, col = tournament)) +
  geom_errorbar(height = .5, position = position_dodge(width=.5), size =2) +
  ylab("Coefficient\n") + 
  xlab("") +
  ggtitle("Y = aces") + 
  scale_color_manual("", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) +
  my_theme +
  coord_flip() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  geom_hline(yintercept = 0, color = "grey") +
  guides(color = guide_legend(override.aes = list(size = 7))) 

nets_ranef = as.data.frame(ranef(n_net_mod, condVar = TRUE)) %>%
  mutate(tournament = gsub("tournament", "", term)) %>%
  filter(., grp == "Serena Williams" | grp == "Rafael Nadal" | grp == "Roger Federer") %>%
  ggplot(., aes(x = as.character(grp), y = condval, ymin = condval- 2*condsd, ymax = condval + 2*condsd, col = tournament)) +
  geom_errorbar(height = .5, position = position_dodge(width=.5), size =2) +
  ylab("Coefficient\n") + 
  xlab("") +
  ggtitle("Y = points won at net") + 
  scale_color_manual("", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) +
  my_theme  +
  coord_flip() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank()) +
  geom_hline(yintercept = 0, color = "grey") +
  guides(color = guide_legend(override.aes = list(size = 7))) 


ue_ranef = as.data.frame(ranef(n_ue_mod, condVar = TRUE)) %>%
  mutate(tournament = gsub("tournament", "", term)) %>%
  filter(., grp == "Serena Williams" | grp == "Rafael Nadal" | grp == "Roger Federer") %>%
  ggplot(., aes(x = as.character(grp),
                y = condval,
                ymin = condval- 2*condsd,
                ymax = condval + 2*condsd, col = tournament)) +
  geom_errorbar(height = .5, position = position_dodge(width=.5), size =2) +
  ylab("Coefficient\n") + 
  xlab("") +
  ggtitle("Y = unforced errors") + 
  scale_color_manual("", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) +
  my_theme  +
  coord_flip() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank()) +
  geom_hline(yintercept = 0, color = "grey") +
  guides(color = guide_legend(override.aes = list(size = 7))) 


ggarrange(aces_ranef, nets_ranef, ue_ranef, nrow=1, ncol=3,
          common.legend = TRUE, legend="bottom", widths = c(.42, .29, .29)) 

if(save_graph){
ggarrange(aces_ranef, nets_ranef, ue_ranef, nrow=1, ncol=3,
          common.legend = TRUE, legend="bottom", widths = c(.42, .29, .29)) %>%
ggsave("../plots/player_effects.jpg", ., height=6, width = graphic_width_long)
}
```



```{r nadal-model}
step_model_n <- courtsports::model_individual(player_name = "Rafael Nadal",
                                              data = gs_partial_players)$final_model

std_res_n <- rstandard(step_model_n)

gn <- ggplot(lm(step_model_n$formula, 
                data = step_model_n$data)) + 
  geom_hline(yintercept = 0, col = "red") +
  geom_point(aes(x=.fitted, y = .stdresid)) + my_theme + ylim(-3, 3) +
  labs(title = "Nadal",
       x = "Predicted Percent of Points Won", y = "Standardized Residuals")

coefs_n <- coefficients(step_model_n)
cov_n <- vcov(step_model_n)

 ## NADAL COEF SIZE

df_n <- data.frame(coeff = names(step_model_n$coeff),
                   ave = step_model_n$coeff, 
                   sd = sqrt(diag(vcov(step_model_n))))
df_n$player <- "Nadal"
```

```{r federer-model}
step_model_f <- courtsports::model_individual(player_name = "Roger Federer", 
                                              data = gs_partial_players,
                                              ref = "Wimbledon")$final_model

gf <- ggplot(lm(step_model_f$formula,
                data = step_model_f$data)) + 
  geom_hline(yintercept = 0, col = "red") +
  geom_point(aes(x=.fitted, y = .stdresid)) + my_theme + ylim(-3, 3) +
  labs(title = "Federer",
       x = "Predicted Percent of Points Won", y = "Standardized Residuals")

coefs_f <- coefficients(step_model_f)
cov_f <- vcov(step_model_f)
 
df_f <- data.frame(coeff = names(step_model_f$coeff),
                   ave = step_model_f$coeff, 
                   sd = sqrt(diag(vcov(step_model_f))))
df_f$player <- "Federer"
```


```{r williams-model}
step_model_w <- courtsports:::model_individual(player_name = "Serena Williams",
                                               data = gs_partial_players,
                                 start_lower = TRUE, ref = "Australian Open")$final_model

std_res_w <- rstandard(step_model_w)

gw <- ggplot(lm(step_model_w$formula,
                data = step_model_w$data)) + 
  geom_hline(yintercept = 0, col = "red") +
  geom_point(aes(x=.fitted, y = .stdresid)) + my_theme + ylim(-3, 3) +
  labs(title = "Williams",
       x = "Predicted Percent of Points Won", y = "Standardized Residuals")

cov_w <- vcov(step_model_w)
coefs_w <- coefficients(step_model_w)

 ## WilliamsCOEF SIZE
df_w <- data.frame(coeff = names(step_model_w$coeff),
                   ave = step_model_w$coeff, 
                   sd = sqrt(diag(vcov(step_model_w))))
df_w$player <- "Williams"
```

## Reference court effects

```{r plot-individual-effects, fig.width=12, fig.height=6}
df <- rbind(df_n, df_w, df_f)
keep_coefs <- which(df$coeff %in% c("(Intercept)", "opponent_rank",
                                    "pct_ace", "pct_bp", "pct_netpt",
                                    "ave_serve_speed", "wue_ratio"))
df <- df[keep_coefs,]

ggplot(df, aes(x = coeff, y = ave, col = player)) +
  geom_errorbar(aes(ymin = ave - 2 *sd, ymax = ave + 2 * sd),
                position = "dodge", width = .3, size = 2) + 
   my_theme +
  # coord_flip() +
  theme(axis.text.x=element_text(angle = 30, hjust = 1)) +
  geom_hline(yintercept = 0, color = "grey") + 
  ggtitle("Fixed effects") +
  scale_color_brewer("", palette = "Dark2") +
  theme(legend.position = "bottom") +
  xlab("") + 
  ylab("Coefficient") +
  scale_x_discrete(labels = c("Intercept", "Opp. Rank", "% Aces",
                              "% Break Points Won", "% Net Points Won",
                              "Ave. Serve Speed", "Winner:UE"))  +
  guides(color = guide_legend(override.aes = list(size = 7)))  +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
  
if(save_graph){
ggsave("../plots/ref-courts-eff.jpg", height=6, width = graphic_width_short)
}
```
  
  
## Logistic parameter effects

```{r, fig.height=7, fig.width=16, fig.align='center'}
# win_colors <- c("#336699", "#339966")
# 
# model_names = c("nocourt_logistic", "base_logistic", "country_logistic", "ind_logistic", 
#                 "ind_logistic_noioc", "ind_int_logistic", "ind_year_logistic")
# 
# model.sums = data.frame(model = model_names, 
#                         aic = rep(NA, length(model_names)), 
#                         edf = rep(NA,length(model_names)))
# model.ests = data.frame()
# ran.effects = data.frame()
# for(mod in 1:nrow(model.sums)){
#   our_name = model_names[mod]
#   model.sums$aic[mod] = extractAIC(get(our_name))[2]
#   model.sums$edf[mod] = extractAIC(get(our_name))[1]
#   betas = tidy(get(our_name))
#   betas$model = our_name
#   if("group" %in% colnames(betas)){
#     model.ests = rbind(model.ests, filter(betas, group == "fixed") %>%
#                          dplyr::select(., -c("group")))
#   } else model.ests = rbind(model.ests, betas)
# }
# 
# model.sums$our_name = c("no_court", "no_random_ef", "country_ef", "ind_ef",
#                     "ind_no_ioc", "ind_intercept", "ind_year_ef")
# model.sums$fixed = c("No country, no tournament",
#                      "all",
#                      "no country, no tournament",
#                      "no tournament",
#                      "no country, no tournament",
#                      "no country",
#                      "no country, no year")
# model.sums$random = c("none",
#                       "none",
#                       "tournament (by country)",
#                       "tournament (by individual)",
#                       "tournament (by individual)",
#                       "intercept (by individual)",
#                       "year (by individual)")
# 
# fixed.effects.plot = model.ests %>%
#   filter(., !grepl("ioc", term)) %>% 
#   filter(., model == 'ind_logistic_noioc') %>%
#   ggplot(., aes(x = term,
#                 y = estimate,
#                 col = model,
#                 ymin = estimate - 2*std.error,
#                 ymax = estimate + 2*std.error)) +
#   geom_errorbar(width = .7, position = position_dodge(), size = 1.5) +
#   my_theme +
#   theme(axis.text.x=element_text(angle = 35, hjust = 1)) +
#   ggtitle("Fixed effects") +
#   scale_color_brewer("",palette = "Dark2") +
#   theme(legend.position = "none") + 
#   xlab("") +
#   ylab("Coefficient") +
#   scale_x_discrete("", breaks = waiver(), 
#                    labels = c("Intercept", "ATP", "Late round", "Op Rank (log)",
#                               "Rank (log)", "2014", "2015", "2016", "2017")) +
#   guides(col = guide_legend(nrow=2)) +
#   geom_hline(yintercept = 0, color = "grey") + 
#   theme(panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank())
# 
# ran_tourn = rbind(ranef(ind_logistic)$name_int, ranef(ind_logistic_noioc)$name_int)
# ran_tourn$model = c(rep("ind_logistic", 
#                         nrow(ranef(ind_logistic)$name_int)), 
#                     rep("ind_logistic_noioc",
#                         nrow(ranef(ind_logistic)$name_int)))
# 
# gs_players$name_int = as.integer(as.factor(gs_players$our_name))
# name_lookup = unique(cbind(gs_players$name, gs_players$name_int))
# name_lookup = name_lookup[order(as.integer(name_lookup[,2])), ]
# 
# top_three_ranef = as.data.frame(ranef(ind_logistic_noioc, condVar = TRUE)) %>%
#   mutate(tournament = gsub("tournament", "", term)) %>%
#   mutate(our_name = name_lookup[,1][as.integer(grp)]) %>% 
#   filter(., our_name == "Serena Williams" | our_name == "Rafael Nadal" | our_name == "Roger Federer") %>%
#   ggplot(., aes(x = our_name, 
#                 y = condval, 
#                 ymin = condval- 2*condsd, 
#                 ymax = condval + 2*condsd, 
#                 color = tournament)) +
#   geom_errorbar(width = .5, position = "dodge",size = 1.5) + 
#   xlab("") + 
#   ylab("Coefficient") + 
#   scale_color_manual("", values=tournament_colors) +
#   my_theme +
#   coord_flip() +
#   ggtitle("Random Effects") +
#   theme(legend.position = "bottom") + 
#   guides(col = guide_legend(nrow=2,
#                             override.aes = list(size = 7))) +
#   geom_hline(yintercept = 0, color = "grey") + 
#   theme(panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank())
# 
# grid.arrange(fixed.effects.plot, top_three_ranef, nrow = 1, widths = c(.45, .55))
# 
# if(save_graph){
# grid.arrange(fixed.effects.plot, top_three_ranef, nrow = 1, widths = c(.45, .55)) %>%
# ggsave("../plots/logistic-parameter-effects.jpg",., height=7, width=graphic_width_long)
# }
```

### Linear fixed effects

```{r, fig.height=6, fig.width=12, fig.align='center'}
fixed.effects.plot.linear <- tidy(n_aces_mod) %>%
  filter(., group == 'fixed') %>%
  mutate(., model = "Aces") %>%
  bind_rows(
    tidy(n_ue_mod) %>%
      filter(., group == 'fixed') %>%
      mutate(., model = "UE")
  ) %>%
  bind_rows(
    tidy(n_net_mod) %>%
      filter(., group == 'fixed') %>%
      mutate(., model = "Net")
  ) %>%
  ggplot(., aes(x = term, y = estimate, 
                ymin = estimate - 2*std.error, 
                ymax = estimate + 2*std.error,
                col = model,
                group = model)) + 
  geom_errorbar(width = .7, position = position_dodge(), size = 1.5) +
  my_theme +
  # coord_flip() +
  theme(axis.text.x=element_text(angle = 35, hjust = 1)) +
  ggtitle("Fixed effects") +
  scale_color_brewer("",palette = "Dark2") +
  theme(legend.position = "bottom") + 
  xlab("") +
  ylab("Coefficient") +
  scale_x_discrete("", 
                   breaks = waiver(), 
                   labels = c("Intercept", "ATP", "Late round", "Op Rank (log)",
                              "Rank (log)", "2014", "2015", "2016", "2017"))  +
  guides(color = guide_legend(override.aes = list(size = 7)))  +
  geom_hline(yintercept = 0, color = "grey") + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
  
if(save_graph){
ggsave("../plots/linear-fixed-effects.jpg", fixed.effects.plot.linear,
       height=6, width = graphic_width_short)
}
```


## Correlation plots

```{r, fig.height=6, fig.width=12, fig.align='center'}
win_colors <- c("#336699", "#339966")

mat <- matrix(c(1, 0, .94, .93,
         0, 1, -.05, -.36,
         .94, -.05, 1, .88,
         .93, -.36, .88, 1), byrow = TRUE, nrow = 4)
colnames(mat) <- c("Aus. Open", "French Open", "US Open", "Wimbledon")
rownames(mat) <- c("Aus. Open", "French Open", "US Open", "Wimbledon")
#
df <- melt(mat)
#
ggplot(df, aes(x = Var1, y = Var2, fill = value)) + geom_tile() +
     geom_tile(color = "white")+
    scale_fill_gradient2(low = win_colors[2], high = win_colors[1], mid = "white", 
                         midpoint = 0, limit = c(-1,1), 
                         space = "Lab", name="Correlation") + 
  labs(x = "", y = "",
       title = "Correlation matrix for random effects")  +
  my_theme

if(save_graph){
ggsave("../plots/correlation.jpg", 
       height=6, width = graphic_width_short)
}
```

  