---
title: "Opening up the court (surface) in tennis grand slams"
date: ' '
output:
  pdf_document:
    toc:  true
header-includes:
  - \usepackage{hyperref}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message = FALSE)

# devtools::install_github("skoval/deuce")
library(deuce)
library(dplyr)
library(tidyr)
library(ggplot2)
library(forcats)
library(stringr)
library(knitr)
library(kableExtra)
library(gridExtra)
library(grid)
library(MASS)
library(ggrepel)
library(broom)
library(lme4)
library(cowplot)
library(ggpubr)
library(reshape2)
# devtools::install_github("shannong19/courtsports")
library(courtsports)
```

```{r graphing-parameters, include = FALSE}
my_theme <-  theme_bw() + # White background, black and white theme
  theme(axis.text = element_text(size = 24),
        text = element_text(size = 28,
        family="serif"),
        plot.title = element_text(hjust = 0.5, size=34),
        plot.subtitle = element_text(hjust = 0.5))

league_colors <- c("#0C2340", "#902BA3")
win_colors <- c("#336699", "#339966")
# with yellow for USA
tournament_colors <- c("#0297DB", "#b06835", "#ffe500", "#54008b")

graphic_width_long <- 16
graphic_width_short <- 12

# SHOULD WE WRITE/SAVE THE GRAPHICS LOCALLY??
save_graph <- FALSE
```


```{r data-cleaning, include = FALSE}
# data(gs)
# data(gs_players)
# data(gs_partial)
# data(gs_partial_players)

data(gs_v2)
data(gs_players_v2)
data(gs_partial_v2)
data(gs_partial_players_v2)
```


# EDA

## Distribution of points earned

```{r, fig.height=8, fig.width=16}
p2 <- ggplot(gs_players_v2) + 
  geom_density(aes(pointswon, ..scaled..,
                   color=tournament, group=tournament, fill = tournament),
                                        size = 3, alpha = 0) + 
  scale_fill_manual(" ", values=tournament_colors,
                                labels = c("Australian Open (Plexicushion)",
                                           "French Open (Clay)",
                                           "US Open (DecoTurf)",
                                           "Wimbledon (Grass)")) + my_theme  +
  guides(fill = guide_legend(override.aes = list(size = 0, alpha = 1),
                              nrow=4, byrow=TRUE)) +
    theme(legend.position="bottom") +
    scale_color_manual(guide=FALSE, values=tournament_colors) +
  facet_wrap(~league, ncol=1) +
  labs(x = "Points", y = "Scaled density")


p1 <- ggplot(gs_players_v2) + 
  geom_density(aes(pointswon, ..scaled..,
                   color = factor(did_win),
                   group = factor(did_win), fill = factor(did_win)),
               size = 3, alpha = 0) + 
  labs(x = "Points", y = " ") +
  scale_fill_manual(" ", values=win_colors, labels = c("Lost match", "Won match")) +
  scale_color_manual(guide = FALSE, values = win_colors) +
  facet_wrap(~league, ncol=1) + 
  my_theme +
  theme(legend.position="bottom",
        legend.spacing.y = unit(1.0, 'cm'),
        legend.margin=ggplot2::margin(t = 2.2, unit='cm'))  +
  guides(fill = guide_legend(override.aes = list(size = 0, alpha = 1),
                             nrow = 2,
                            byrow=TRUE),
        title.hjust = 5) 

grid.arrange(p2, p1, ncol=2)

if(save_graph){
  grid.arrange(p2, p1, ncol=2) %>%
  ggsave("../plots/points_per_match_v2.jpg", ., height=8, width=graphic_width_long)
}
```


## Home court advantage 

```{r}
france_wins <- dplyr::filter(gs_players_v2, ioc == "FRA", round < "QF") %>% 
  dplyr::group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

us_wins <- dplyr::filter(gs_players_v2, ioc == "USA", round < "QF") %>% 
  dplyr::group_by(tournament, round) %>% 
  dplyr::summarize(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

aus_wins <- filter(gs_players_v2, ioc == "AUS", round < "QF") %>% 
  group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

gbr_wins <- filter(gs_players_v2, ioc == "GBR", round < "QF") %>% 
  group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

```

```{r, echo=TRUE}
dplyr::filter(gs_players_v2, ioc == "USA", round < "QF")  %>% nrow()
dplyr::filter(gs_players_v2, ioc == "USA", round < "QF")  %>% 
  pull(name) %>% unique() %>% length()

dplyr::filter(gs_players_v2, ioc == "FRA", round < "QF")  %>% nrow()
dplyr::filter(gs_players_v2, ioc == "FRA", round < "QF")  %>%
  pull(name) %>% unique() %>% length()

dplyr::filter(gs_players_v2, ioc == "AUS", round < "QF")  %>% nrow()
dplyr::filter(gs_players_v2, ioc == "AUS", round < "QF")  %>% 
  pull(name) %>% unique() %>% length()

dplyr::filter(gs_players_v2, ioc == "GBR", round < "QF")  %>% nrow()
dplyr::filter(gs_players_v2, ioc == "GBR", round < "QF")  %>% 
  pull(name) %>% unique() %>% length()
```

```{r, fig.height=5.5, fig.width=16, fig.align='center'}
p1<- ggplot(france_wins, aes(round, win_prop,
                             color=tournament, group=tournament,
                             size = tournament,
                             linetype = tournament)) + 
  labs(title = "French players",
       # subtitle = "53 players, n=828",
       subtitle = "66 players, n=1119",
       x = "", y = " ") + 
  geom_line() + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
scale_size_manual(guide = FALSE,
                   values = c(1, 3, 1, 1)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(2, 1, 2, 2)) + ylim(c(0, 1))

p2 <- ggplot(us_wins, aes(round, win_prop,
                          color=tournament, group=tournament,
                          size = tournament,
                          linetype=tournament)) + 
  labs(title = "USA players",
       subtitle = "94 players, n=1512",
      # subtitle = "81 players, n=1046",
              x = "", y = " ") + 
    geom_line() + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
  scale_size_manual(guide = FALSE,
                   values = c(1, 1, 3, 1)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(2, 2, 1, 2)) + ylim(c(0, 1))

p3 <- ggplot(aus_wins, aes(round, win_prop,
                           color=tournament, group=tournament, # alpha = tournament,
                           size = tournament,
                           linetype = tournament)) + 
  labs(title = "Aus. players",
       subtitle = "47 players, n=576",
              # subtitle = "40 players, n=376",
       x = "", y = "Win proportion") + 
    geom_line() + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
  scale_size_manual(guide = FALSE,
                   values = c(3, 1, 1, 1)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(1, 2, 2, 2)) + ylim(c(0, 1))

p4 <- ggplot(gbr_wins, aes(round, win_prop, color=tournament,
                           group=tournament, fill = tournament,
                           size = tournament,
                           linetype = tournament)) + 
  geom_line() + 
  labs(title = "British players",
       subtitle = "26 players, n=322",
              # subtitle = "21 players, n=249",
       x = "", y = " ") + 
  scale_color_manual(" ", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme +
  guides(color = guide_legend(override.aes = list(size = 7)))  + 
  scale_size_manual(guide = FALSE,
                   values = c(1, 1, 1, 3)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(2, 2, 2, 1)) + ylim(c(0, 1))


ggarrange(p3, p1, p2,  p4, nrow=1, ncol=4, common.legend = TRUE, legend="bottom") %>%
grid.arrange(.,
             bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
                           just = "left",
                           gp=gpar(fontfamily="serif", fontsize = 20))) 
if(save_graph){
ggarrange(p3, p1, p2,  p4, nrow=1, ncol=4, common.legend = TRUE, legend="bottom") %>%
grid.arrange(.,
             bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
                           just = "left",
                           gp=gpar(fontfamily="serif", fontsize = 20))) %>%
  ggsave("../plots/home_court_v2.jpg", ., height=5.5, width=graphic_width_long)
}
```

### Subset: players who played in all 4 tournaments

```{r, fig.height=5, fig.width=16, fig.align='center'}
all4 <- 
  gs_players_v2 %>% 
  dplyr::group_by(name) %>% 
  dplyr::summarize(tourn_n = length(unique(tournament))) %>%
  dplyr::filter(tourn_n == 4) %>%
  dplyr::pull(name)

france_wins <- dplyr::filter(gs_players_v2, ioc == "FRA", round < "QF", name %in% all4) %>% 
  dplyr::group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

us_wins <- dplyr::filter(gs_players_v2, ioc == "USA", round < "QF", name %in% all4) %>% 
  dplyr::group_by(tournament, round) %>% 
  dplyr::summarize(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

aus_wins <- filter(gs_players_v2, ioc == "AUS", round < "QF", name %in% all4) %>% 
  group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

gbr_wins <- filter(gs_players_v2, ioc == "GBR", round < "QF", name %in% all4) %>% 
  group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()))

p1<- ggplot(france_wins, aes(round, win_prop,
                             color=tournament, group=tournament,
                             size = tournament,
                             linetype = tournament)) + 
  labs(title = "French players",
       x = "", y = " ") + 
  geom_line() + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
scale_size_manual(guide = FALSE,
                   values = c(1, 3, 1, 1)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(2, 1, 2, 2)) + ylim(c(0, 1))

p2 <- ggplot(us_wins, aes(round, win_prop,
                          color=tournament, group=tournament,
                          size = tournament,
                          linetype=tournament)) + 
  labs(title = "USA players",
              x = "", y = " ") + 
    geom_line() + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
  scale_size_manual(guide = FALSE,
                   values = c(1, 1, 3, 1)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(2, 2, 1, 2)) + ylim(c(0, 1))

p3 <- ggplot(aus_wins, aes(round, win_prop,
                           color=tournament, group=tournament, # alpha = tournament,
                           size = tournament,
                           linetype = tournament)) + 
  labs(title = "Aus. players",
       x = "", y = "Win proportion") + 
    geom_line() + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme   + 
  scale_size_manual(guide = FALSE,
                   values = c(3, 1, 1, 1)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(1, 2, 2, 2)) + ylim(c(0, 1))


p4 <- ggplot(gbr_wins, aes(round, win_prop, color=tournament,
                           group=tournament, fill = tournament,
                           size = tournament,
                           linetype = tournament)) + 
  geom_line() + 
  labs(title = "British players",
       x = "", y = " ") + 
  scale_color_manual(" ", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme +
  guides(color = guide_legend(override.aes = list(size = 7)))  + 
  scale_size_manual(guide = FALSE,
                   values = c(1, 1, 1, 3)) + 
  scale_linetype_manual(guide = FALSE,
                   values = c(2, 2, 2, 1)) + ylim(c(0, 1))

ggarrange(p3, p1, p2,  p4, nrow=1, ncol=4, common.legend = TRUE, legend="bottom") %>%
grid.arrange(.,
             bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
                           just = "left",
                           gp=gpar(fontfamily="serif", fontsize = 20))) 

if(save_graph){
ggarrange(p3, p1, p2,  p4, nrow=1, ncol=4, common.legend = TRUE, legend="bottom") %>%
grid.arrange(.,
             bottom = textGrob("Note: we only look at the first 4 rounds due to decreasing sample size",
                           just = "left",
                           gp=gpar(fontfamily="serif", fontsize = 20))) %>%
  ggsave("../plots/home_court_all4_v2.jpg", ., height=5, width=graphic_width_long)
}
```


## Spaniards on clay

```{r}
spain_wins <- filter(gs_players_v2, ioc == "ESP", round < "QF") %>% 
  group_by(tournament, round) %>% 
  dplyr::summarise(win_prop = mean(did_win, na.rm=TRUE),
            win_prop_se = sqrt(win_prop*(1-win_prop)/n()),
            avg_ranking = mean(rank),
            rank_se = sd(rank)/sqrt(n()),
            n_size = n(),
            med_ranking = median(rank, na.rm = TRUE))

prop.table(with(filter(gs_players_v2, ioc == "ESP", round == "R128"),
                table(did_win, tournament)), 2)

with(filter(gs_players_v2, ioc == "ESP", round == "R128"),
                table(did_win, tournament))

```

### Chi-squared tests

```{r}
################################################################################
# TESTS FOR PAPER
################################################################################
with(filter(gs_players_v2, ioc == "ESP", round == "R128"),
     table(did_win, tournament)) %>%
  chisq.test(correct = TRUE)
with(filter(gs_players_v2, ioc == "ESP", round == "R64"),
     table(did_win, tournament)) %>%
  chisq.test(correct = TRUE)
with(filter(gs_players_v2, ioc == "ESP", round == "R32"),
     table(did_win, tournament)) %>%
  chisq.test(correct = TRUE)
with(filter(gs_players_v2, ioc == "ESP", round == "R16"),
     table(did_win, tournament)) %>%
  chisq.test(correct = TRUE)
```


```{r, fig.height=6, fig.width=16, fig.align='center'}
p1 <- ggplot(spain_wins, aes(round, win_prop, color=tournament, group=tournament)) + 
  labs(title = "Win proportion among Spaniards",
       x = "", y = "Win proportion") + 
    geom_line(size=3) + 
  scale_color_manual(guide=FALSE, values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme  

p2 <- ggplot(spain_wins, aes(round, avg_ranking, color=tournament, group=tournament, fill = tournament)) + 
  geom_line(size=3) + 
  labs(title = "Average ranking among Spaniards",
       x = " ",
       y = "Average rank") + 
  scale_color_manual(" ", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme +
  guides(color = guide_legend(override.aes = list(size = 7))) 


ggarrange( p1, p2, nrow=1, ncol=2, common.legend = TRUE, legend="bottom") 

if(save_graph){
ggarrange( p1, p2, nrow=1, ncol=2, common.legend = TRUE, legend="bottom") %>%
  ggsave("../plots/spainards_v2.jpg", ., height=6, width=graphic_width_long)
}


ggplot(spain_wins, aes(round, med_ranking, color=tournament, group=tournament, fill = tournament)) + 
  geom_line(size=3) + 
  labs(title = "Median ranking among Spaniards",
       x = " ",
       y = "Median rank") + 
  scale_color_manual(" ", values=tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)",
                                           "French Open\n(Clay)",
                                           "US Open\n(DecoTurf)",
                                           "Wimbledon\n(Grass)")) + my_theme +
  guides(color = guide_legend(override.aes = list(size = 7))) 


```


## Unforced errors and aces

```{r, fig.width=12, fig.height=6, fig.align='center'}
ggplot(gs_partial_v2, aes(w_n_ue + l_n_ue, w_n_aces + l_n_aces,
                           label = tournament, color=tournament)) + 
  geom_jitter(size=1.8) + # used to be size=2 in v1
  labs( title = "Distribution of errors and aces differ by tournament",
        x = "Total unforced errors", y = "Total aces") +
  my_theme + scale_color_manual("Tournament",
                                values = tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)\n",
                                           "French Open\n(Clay)\n",
                                           "US Open\n(DecoTurf)\n",
                                           "Wimbledon\n(Grass)\n")) +
  stat_ellipse(type="t", size = 2) +
  guides(color = guide_legend(override.aes = list(size = 7, shape=15))) 

if(save_graph){
ggsave("../plots/errors_aces2_v2.jpg", height = 6, width = graphic_width_short)
}
```


## Tall players and aces

```{r, fig.width=16, fig.height=7, fig.align='center'}
set.seed(8)

atp_servers <- c("Ivo Karlovic", "John Isner", "Rafael Nadal",
                 "Roger Federer", "Andy Murray")
atp_servers <- sapply(atp_servers,
                      function(x) return(sample(which(gs_players_v2$name == x), 2))) %>%
  as.numeric() %>% gs_players_v2[., ]

wta_servers <- c("Karolina Pliskova", "Caroline Wozniacki",
                 "Venus Williams", "Serena Williams", "Madison Keys")
wta_servers <- sapply(wta_servers,
                      function(x) return(sample(which(gs_players_v2$name == x), 2))) %>%
  as.numeric() %>% gs_players_v2[., ]

p_atp <- gs_players_v2 %>% filter(league == "ATP") %>%
ggplot( aes(log(ht+1), log(ace+1))) + 
  geom_jitter(aes(color = tournament), size=1.5) + 
  # scale_color_manual(" ", values = tournament_colors) + 
  geom_smooth( method = "lm", color="black") + 
  geom_label_repel(data=atp_servers,
            aes(log(ht+1), log(ace+1), label=name),
            alpha=.8, seed=1234, show.legend=FALSE, size = 8) + 
  geom_label_repel(data=atp_servers,
            aes(log(ht+1), log(ace+1), label = name),
            seed=1234, fill=NA, show.legend=FALSE, size = 8) +
  labs(x = "log(height + 1)", title = "ATP") +
  my_theme + scale_color_manual("Tournament",
                                values = tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)\n",
                                           "French Open\n(Clay)\n",
                                           "US Open\n(DecoTurf)\n",
                                           "Wimbledon\n(Grass)\n")) +
  guides(color = guide_legend(override.aes = list(size = 7, shape=15)))

p_wta <- gs_players_v2 %>% filter(league == "WTA") %>%
ggplot(aes(log(ht+1), log(ace+1))) + 
  geom_jitter(aes(color = tournament)) + 
  # scale_color_manual(" ", values = tournament_colors) + 
  geom_smooth(method = "lm", color="black") + 
  geom_label_repel(data=wta_servers,
            aes(log(ht+1), log(ace+1), label=name),
            alpha=.8, seed=1234, show.legend=FALSE, size = 8) + 
  geom_label_repel(data=wta_servers,
            aes( log(ht+1), log(ace+1), label=name),
            seed=1234, fill=NA, show.legend=FALSE, size = 8) +
  labs(x = "log(height + 1)", title = "WTA")+
  my_theme + scale_color_manual("Tournament",
                                values = tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)\n",
                                           "French Open\n(Clay)\n",
                                           "US Open\n(DecoTurf)\n",
                                           "Wimbledon\n(Grass)\n")) +
  guides(color = guide_legend(override.aes = list(size = 7, shape=15))) 

ggarrange(p_atp, p_wta, common.legend = TRUE, legend="bottom") 

if(save_graph){
ggsave("../plots/aces2_v2.jpg", height=7, width=graphic_width_long)
}
```


#### Using ace percentage

```{r, fig.width=16, fig.height=8, fig.align='center'}
set.seed(8)

atp_servers <- c("Ivo Karlovic", "John Isner", "Rafael Nadal",
                 "Roger Federer", "Andy Murray")
atp_servers <- sapply(atp_servers,
                      function(x) return(sample(which(gs_players_v2$name == x), 2))) %>%
  as.numeric() %>% gs_players_v2[., ]

wta_servers <- c("Karolina Pliskova", "Caroline Wozniacki",
                 "Venus Williams", "Serena Williams", "Madison Keys")
wta_servers <- sapply(wta_servers,
                      function(x) return(sample(which(gs_players_v2$name == x), 2))) %>%
  as.numeric() %>% gs_players_v2[., ]

p_atp_percent <- gs_players_v2 %>% filter(league == "ATP") %>%
ggplot( aes(log(ht+1), ace/svpt)) + 
  geom_jitter(aes(color = tournament), size=1.5) + 
  # scale_color_manual(" ", values = tournament_colors) + 
  geom_smooth( method = "lm", color="black") + 
  geom_label_repel(data=atp_servers,
            aes(log(ht+1), ace/svpt, label=name),
            alpha=.8, seed=1234, show.legend=FALSE, size = 7) + 
  geom_label_repel(data=atp_servers,
            aes(log(ht+1), ace/svpt, label = name),
            seed=1234, fill=NA, show.legend=FALSE, size = 7) +
  labs(x = "log(height + 1)", y = "ace% = aces / serves", title = "ATP") +
  my_theme + scale_color_manual("Tournament",
                                values = tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)\n",
                                           "French Open\n(Clay)\n",
                                           "US Open\n(DecoTurf)\n",
                                           "Wimbledon\n(Grass)\n")) +
  guides(color = guide_legend(override.aes = list(size = 7, shape=15)))

p_wta_percent <- gs_players_v2 %>% filter(league == "WTA") %>%
ggplot(aes(log(ht+1), ace/svpt)) + 
  geom_jitter(aes(color = tournament)) + 
  # scale_color_manual(" ", values = tournament_colors) + 
  geom_smooth(method = "lm", color="black") + 
  geom_label_repel(data=wta_servers,
            aes(log(ht+1), ace/svpt, label=name),
            alpha=.8, seed=1234, show.legend=FALSE, size = 7) + 
  geom_label_repel(data=wta_servers,
            aes( log(ht+1), ace/svpt, label=name),
            seed=1234, fill=NA, show.legend=FALSE, size = 7) +
  labs(x = "log(height + 1)", y = "ace%  = aces / serves", title = "WTA")+
  my_theme + scale_color_manual("Tournament",
                                values = tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)\n",
                                           "French Open\n(Clay)\n",
                                           "US Open\n(DecoTurf)\n",
                                           "Wimbledon\n(Grass)\n")) +
  guides(color = guide_legend(override.aes = list(size = 7, shape=15))) 

ggarrange(p_atp_percent, p_wta_percent, common.legend = TRUE, legend="bottom") 

if(save_graph){
ggsave("../plots/aces2_percent_v2.jpg", height=8, width=graphic_width_long)
}
```



#### Using ace percentage.... one dot per tournament (colored)

```{r, fig.width=16, fig.height=8, fig.align='center'}
set.seed(8)

maxish <- function(x){
  xx <- na.omit(unique(x))
  return(ifelse(length(xx) > 1, max(xx), xx))
}

atp_servers <- c("Ivo Karlovic", "John Isner", "Rafael Nadal",
                 "Roger Federer", "Andy Murray")

wta_servers <- c("Karolina Pliskova", "Caroline Wozniacki",
                 "Venus Williams", "Serena Williams", "Madison Keys")


atp_ace_ht_tour <-   gs_players_v2 %>% 
  filter(league == "ATP") %>%
  dplyr::group_by(name, tournament) %>%
  dplyr::summarise(ht = maxish(ht),
                   avg_ace_perc = mean(ace/svpt, na.rm=TRUE),
                   med_ace_perc = median(ace/svpt, na.rm=TRUE),
                   count_n = n())

wta_ace_ht_tour <-   gs_players_v2 %>% 
  filter(league == "WTA") %>%
  dplyr::group_by(name, tournament) %>%
  dplyr::summarise(ht = maxish(ht),
                   avg_ace_perc = mean(ace/svpt, na.rm=TRUE),
                   med_ace_perc = median(ace/svpt, na.rm=TRUE),
                   count_n = n())

# atp_servers <- sapply(ungroup(atp_ace_ht_tour),
#                       function(x) return(sample(which(ungroup(atp_ace_ht_tour)$name == x), 2))) %>%
#   as.numeric() %>% ungroup(atp_ace_ht_tour)[., ]
# 
# wta_servers <- sapply(wta_ace_ht_tour,
#                       function(x) return(sample(which(wta_ace_ht_tour$name == x), 2))) %>%
#   as.numeric() %>% gs_players_v2[., ]


p_atp_percent <- 
atp_ace_ht_tour %>% # could also try median
ggplot(aes(ht, med_ace_perc)) + 
  geom_jitter(aes(color = tournament), size=1.5) + 
  # scale_color_manual(" ", values = tournament_colors) +
  geom_smooth(aes(color = tournament), method = "lm") + 
  geom_label_repel(data=dplyr::filter(atp_ace_ht_tour, name %in% atp_servers),
            aes(ht, med_ace_perc, label=name, color = tournament),
            alpha=.8, seed=1234, show.legend=FALSE, size = 5,
            nudge_y = c(-.075, 0, 0, -0.05,0.02 ),
            nudge_x = c(5, 5, -5, -3, 0)) + 
  geom_label_repel(data=dplyr::filter(atp_ace_ht_tour, name %in% atp_servers),
            aes(ht, med_ace_perc, label = name, color = tournament),
            seed=1234, fill=NA, show.legend=FALSE, size = 5,
            nudge_y = c(-.075, 0, 0, -0.05,0.02 ),
            nudge_x = c(5, 5, -5, -3, 0)) +
  labs(x = "Height in cm", y = "Median ace% per match", title = "ATP") +
  my_theme +
  scale_color_manual("Tournament",
                                values = tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)\n",
                                           "French Open\n(Clay)\n",
                                           "US Open\n(DecoTurf)\n",
                                           "Wimbledon\n(Grass)\n")) +
# +
#   guides(color = guide_legend(override.aes = list(size = 7, shape=15))) + 
facet_wrap(~tournament) +
theme(legend.position="none")

p_atp_percent

if(save_graph){
ggsave("../plots/ace_ht_facet_atp_v2.jpg", height=8, width=graphic_width_short)
}

p_wta_percent <- 
wta_ace_ht_tour %>% # could also try median
ggplot(aes(ht, med_ace_perc)) + 
  geom_jitter(aes(color = tournament), size=1.5) + 
  # scale_color_manual(" ", values = tournament_colors) +
  geom_smooth(aes(color = tournament), method = "lm") + 
  geom_label_repel(data=dplyr::filter(wta_ace_ht_tour, name %in% wta_servers),
            aes(ht, med_ace_perc, label=name, color = tournament),
            seed=1234, fill=NA, show.legend=FALSE, size = 5,
            nudge_y = rep(c(-.1, .06, 0.06, 0.08, -0.1), 4),
            nudge_x = rep(c(-5, 0, 0, -7, 0), 4)) +
  geom_label_repel(data=dplyr::filter(wta_ace_ht_tour, name %in% wta_servers),
            aes(ht, med_ace_perc, label = name, color = tournament),
            seed=1234, fill=NA, show.legend=FALSE, size = 5,
            nudge_y = rep(c(-.1, .06, 0.06, 0.08, -0.1), 4),
            nudge_x = rep(c(-5, 0, 0, -7, 0), 4)) +
  labs(x = "Height in cm", y = "Median ace% per match", title = "WTA") +
  my_theme +
  scale_color_manual("Tournament",
                                values = tournament_colors,
                                labels = c("Australian Open\n(Plexicushion)\n",
                                           "French Open\n(Clay)\n",
                                           "US Open\n(DecoTurf)\n",
                                           "Wimbledon\n(Grass)\n")) +
# +
#   guides(color = guide_legend(override.aes = list(size = 7, shape=15))) + 
facet_wrap(~tournament) +
theme(legend.position="none") + 
  ylim(c(-0.02, 0.2))

p_wta_percent

if(save_graph){
ggsave("../plots/ace_ht_facet_wta_v2.jpg", height=8, width=graphic_width_short)
}

```




#### Using ace percentage.... one dot per player - black white

```{r, fig.width=16, fig.height=8, fig.align='center'}
set.seed(8)

atp_ace_ht <-   gs_players_v2 %>% 
  filter(league == "ATP") %>%
  dplyr::group_by(name) %>%
  dplyr::summarise(ht = maxish(ht),
                   avg_ave_perc = mean(ace/svpt, na.rm=TRUE),
                   med_ace_perc = median(ace/svpt, na.rm=TRUE),
                   count_n = n())

wta_ace_ht <-   gs_players_v2 %>% 
  filter(league == "WTA") %>%
  dplyr::group_by(name) %>%
  dplyr::summarise(ht = maxish(ht),
                   avg_ave_perc = mean(ace/svpt, na.rm=TRUE),
                   med_ace_perc = median(ace/svpt, na.rm=TRUE),
                   count_n = n())


p_atp_percent <- atp_ace_ht %>% # could also try median
ggplot( aes(ht, med_ace_perc)) + 
  geom_jitter(size=1.5, width = 0.8) + 
  geom_smooth( method = "lm", color="black") + 
  geom_label_repel(data=dplyr::filter(atp_ace_ht, name %in% atp_servers),
            aes(ht, med_ace_perc, label=name),
            alpha=.8, seed=1234, show.legend=FALSE, size = 6,
            nudge_y = c(-.025, 0, -.01, -0.05,0.02),
            nudge_x = c(6, -2, 0, -3, -1)) +
  geom_label_repel(data=dplyr::filter(atp_ace_ht, name %in% atp_servers),
            aes(ht, med_ace_perc, label = name),
            seed=1234, fill=NA, show.legend=FALSE, size = 6,
            nudge_y = c(-.025, 0, -0.01, -0.05,0.02),
            nudge_x = c(6, -2, 0, -3, -1)) +
  labs(x = "Height in cm", y = "Median ace% per match", title = "ATP") +
  my_theme 
# + 
#   ylim(c(0, 0.25))
p_atp_percent


p_wta_percent <- wta_ace_ht %>% # could also try median
ggplot( aes(ht, med_ace_perc)) + 
  geom_jitter(size=1.5, width=.6) + 
  geom_smooth( method = "lm", color="black") + 
  geom_label_repel(data=dplyr::filter(wta_ace_ht, name %in% wta_servers),
            aes(ht, med_ace_perc, label=name),
            alpha=.8, seed=1234, show.legend=FALSE, size = 6,
            nudge_y = c(-.02, .01, 0.01, -0.01, -0.03 ),
            nudge_x = c(-3, 5, -3, 0, 0)) + 
  geom_label_repel(data=dplyr::filter(wta_ace_ht, name %in% wta_servers),
            aes(ht, med_ace_perc, label = name),
            seed=1234, fill=NA, show.legend=FALSE, size = 6,
            nudge_y = c(-.02, .01, 0.01, -0.01, -0.03 ),
            nudge_x = c(-3, 5, -3, 0, 0)) +
  labs(x = "Height in cm", y = "Median ace% per match", title = "WTA") +
  my_theme
# + 
#   ylim(c(0, 0.25))

p_wta_percent


ggarrange(p_atp_percent, NULL, p_wta_percent, common.legend = TRUE, legend="bottom", widths = c(1, 0.08, 1), nrow = 1) 

if(save_graph){
ggsave("../plots/aces_median_percent_BW2_v2.jpg", height=8, width=graphic_width_long)
}


p_atp_percent <- atp_ace_ht %>% # could also try median
ggplot( aes(ht, med_ace_perc)) + 
  geom_jitter(size=1.5, width = 0.8) + 
  geom_smooth( method = "lm", color="black") + 
  geom_label_repel(data=dplyr::filter(atp_ace_ht, name %in% atp_servers),
            aes(ht, med_ace_perc, label=name),
            alpha=.8, seed=1234, show.legend=FALSE, size = 5,
            nudge_y = c(-.075, 0, 0, -0.05,0.02 ),
            nudge_x = c(5, 5, -5, -3, 0)) +
  geom_label_repel(data=dplyr::filter(atp_ace_ht, name %in% atp_servers),
            aes(ht, med_ace_perc, label = name),
            seed=1234, fill=NA, show.legend=FALSE, size = 5,
            nudge_y = c(-.075, 0, 0, -0.05,0.02 ),
            nudge_x = c(5, 5, -5, -3, 0)) +
  labs(x = "Height in cm", y = "Median ace% per match", title = "ATP") +
  my_theme +
  ylim(c(0, 0.25))


p_wta_percent <- wta_ace_ht %>% # could also try median
ggplot( aes(ht, med_ace_perc)) + 
  geom_jitter(size=1.5, width = 0.6) + 
  geom_smooth( method = "lm", color="black") + 
  geom_label_repel(data=dplyr::filter(wta_ace_ht, name %in% wta_servers),
            aes(ht, med_ace_perc, label=name),
            alpha=.8, seed=1234, show.legend=FALSE, size = 5,
            nudge_y = c(-.02, .01, 0.01, -0.01, -0.01),
            nudge_x = c(-1, 5, 5, 0, 0)) + 
  geom_label_repel(data=dplyr::filter(wta_ace_ht, name %in% wta_servers),
            aes(ht, med_ace_perc, label = name),
            seed=1234, fill=NA, show.legend=FALSE, size = 5,
            nudge_y = c(-.02, .01, 0.01, -0.01, -0.01),
            nudge_x = c(-1, 5, 5, 0, 0)) +
  labs(x = "Height in cm", y = " ", title = "WTA") +
  my_theme +
  ylim(c(0, 0.25))


# ggarrange(p_atp_percent, p_wta_percent, common.legend = TRUE, legend="bottom",
#           nrow=1) 
# 
# if(save_graph){
# ggsave("../plots/aces_median_percent_BW1_v2.jpg", height=8, width=graphic_width_long)
# }




p_atp_percent <- atp_ace_ht %>% # could also try median
ggplot( aes(ht, avg_ave_perc)) + 
  geom_jitter(size=1.5, width = 0.8) + 
  geom_smooth( method = "lm", color="black") + 
  geom_label_repel(data=dplyr::filter(atp_ace_ht, name %in% atp_servers),
            aes(ht, avg_ave_perc, label=name),
            alpha=.8, seed=1234, show.legend=FALSE, size = 6,
            nudge_y = c(-.025, 0, -.01, -0.05,0.02),
            nudge_x = c(6, -2, 0, -3, -1)) +
  geom_label_repel(data=dplyr::filter(atp_ace_ht, name %in% atp_servers),
            aes(ht, avg_ave_perc, label = name),
            seed=1234, fill=NA, show.legend=FALSE, size = 6,
            nudge_y = c(-.025, 0, -0.01, -0.05,0.02),
            nudge_x = c(6, -2, 0, -3, -1)) +
  labs(x = "Height in cm", y = "Mean ace% per match", title = "ATP") +
  my_theme 
# + 
#   ylim(c(0, 0.25))
p_atp_percent


p_wta_percent <- wta_ace_ht %>% # could also try median
ggplot( aes(ht, avg_ave_perc)) + 
  geom_jitter(size=1.5, width=.6) + 
  geom_smooth( method = "lm", color="black") + 
  geom_label_repel(data=dplyr::filter(wta_ace_ht, name %in% wta_servers),
            aes(ht, avg_ave_perc, label=name),
            alpha=.8, seed=1234, show.legend=FALSE, size = 6,
            nudge_y = c(-.02, .01, 0.01, -0.01, -0.03 ),
            nudge_x = c(-3, 5, -3, 0, 0)) + 
  geom_label_repel(data=dplyr::filter(wta_ace_ht, name %in% wta_servers),
            aes(ht, avg_ave_perc, label = name),
            seed=1234, fill=NA, show.legend=FALSE, size = 6,
            nudge_y = c(-.02, .01, 0.01, -0.01, -0.03 ),
            nudge_x = c(-3, 5, -3, 0, 0)) +
  labs(x = "Height in cm", y = "Mean ace% per match", title = "WTA") +
  my_theme
# + 
#   ylim(c(0, 0.25))

p_wta_percent


ggarrange(p_atp_percent, NULL, p_wta_percent, common.legend = TRUE, legend="bottom", widths = c(1, 0.08, 1), nrow = 1) 

if(save_graph){
ggsave("../plots/aces_mean_percent_v2.jpg", height=8, width=graphic_width_long)
}

```


<!-- #### Using ace percentage.... one dot per tournament (black white) -->

<!-- ```{r, fig.width=16, fig.height=8, fig.align='center'} -->
<!-- set.seed(8) -->

<!-- maxish <- function(x){ -->
<!--   xx <- na.omit(unique(x)) -->
<!--   return(ifelse(length(xx) > 1, max(xx), xx)) -->
<!-- } -->

<!-- atp_servers <- c("Ivo Karlovic", "John Isner", "Rafael Nadal", -->
<!--                  "Roger Federer", "Andy Murray") -->

<!-- wta_servers <- c("Karolina Pliskova", "Caroline Wozniacki", -->
<!--                  "Venus Williams", "Serena Williams", "Madison Keys") -->


<!-- atp_ace_ht_tour <-   gs_players_v2 %>%  -->
<!--   filter(league == "ATP") %>% -->
<!--   dplyr::group_by(name, tournament) %>% -->
<!--   dplyr::summarise(ht = maxish(ht), -->
<!--                    avg_ace_perc = mean(ace/svpt, na.rm=TRUE), -->
<!--                    med_ace_perc = median(ace/svpt, na.rm=TRUE), -->
<!--                    count_n = n()) -->

<!-- wta_ace_ht_tour <-   gs_players_v2 %>%  -->
<!--   filter(league == "WTA") %>% -->
<!--   dplyr::group_by(name, tournament) %>% -->
<!--   dplyr::summarise(ht = maxish(ht), -->
<!--                    avg_ace_perc = mean(ace/svpt, na.rm=TRUE), -->
<!--                    med_ace_perc = median(ace/svpt, na.rm=TRUE), -->
<!--                    count_n = n()) -->

<!-- atp_servers <- sapply(atp_servers, -->
<!--                       function(x) return(sample(which(gs_players_v2$name == x), 2))) %>% -->
<!--   as.numeric() %>%  -->
<!--   gs_players_v2[., ]  %>% -->
<!--   dplyr::mutate(med_ace_perc = median(ace/svpt, na.rm=TRUE)) -->

<!-- wta_servers <- sapply(wta_servers, -->
<!--                       function(x) return(sample(which(gs_players_v2$name == x), 2))) %>% -->
<!--   as.numeric() %>% gs_players_v2[., ] %>% -->
<!--   dplyr::mutate(med_ace_perc = median(ace/svpt, na.rm=TRUE)) -->


<!-- p_atp_percent <-  -->
<!-- atp_ace_ht_tour %>% # could also try median -->
<!-- ggplot(aes(ht, med_ace_perc)) +  -->
<!--   geom_jitter( size=1.5) +  -->
<!--   # scale_color_manual(" ", values = tournament_colors) + -->
<!--   geom_smooth( method = "lm", color = "black") +  -->
<!--   geom_label_repel(data=atp_servers, -->
<!--             aes(ht, med_ace_perc, label=name), -->
<!--             alpha=.8, seed=1234, show.legend=FALSE, size = 7, -->
<!--             nudge_y = c(-.075, 0, 0, -0.05,0.02 ), -->
<!--             nudge_x = c(5, 5, -5, -3, 0)) +  -->
<!--   geom_label_repel(data=atp_servers, -->
<!--             aes(ht, med_ace_perc, label = name), -->
<!--             seed=1234, fill=NA, show.legend=FALSE, size = 7, -->
<!--             nudge_y = c(-.075, 0, 0, -0.05,0.02 ), -->
<!--             nudge_x = c(5, 5, -5, -3, 0)) + -->
<!--   labs(x = "Height in cm", y = "Median ace% per match", title = "ATP") + -->
<!--    my_theme # + -->
<!-- #   scale_color_manual("Tournament", -->
<!-- #                                 values = tournament_colors, -->
<!-- #                                 labels = c("Australian Open\n(Plexicushion)\n", -->
<!-- #                                            "French Open\n(Clay)\n", -->
<!-- #                                            "US Open\n(DecoTurf)\n", -->
<!-- #                                            "Wimbledon\n(Grass)\n")) + -->
<!-- # # + -->
<!-- # #   guides(color = guide_legend(override.aes = list(size = 7, shape=15))) +  -->
<!-- # facet_wrap(~tournament) + -->
<!-- # theme(legend.position="none") -->

<!-- p_atp_percent -->

<!-- p_wta_percent <-  -->
<!-- wta_ace_ht_tour %>% # could also try median -->
<!-- ggplot(aes(ht, med_ace_perc)) +  -->
<!--   geom_jitter(size=1.5) +  -->
<!--   # scale_color_manual(" ", values = tournament_colors) + -->
<!--   geom_smooth(method = "lm", color = "black") +  -->
<!--   geom_label_repel(data=wta_servers, -->
<!--             aes(ht, med_ace_perc, label=name), -->
<!--             seed=1234, fill=NA, show.legend=FALSE, size = 5) + -->
<!--             # nudge_y = rep(c(-.1, .06, 0.06, 0.08, -0.1), 4), -->
<!--             # nudge_x = rep(c(-5, 0, 0, -7, 0), 4)) + -->
<!--   geom_label_repel(data=wta_servers, -->
<!--             aes(ht, med_ace_perc, label = name), -->
<!--             seed=1234, fill=NA, show.legend=FALSE, size = 5) + -->
<!--             # nudge_y = c(-.1, .06, 0.06, 0.08, -0.1), -->
<!--             # nudge_x = c(-5, 0, 0, -7, 0)) + -->
<!--   labs(x = "Height in cm", y = "Median ace% per match", title = "WTA") + -->
<!--   my_theme # + -->
<!-- #   scale_color_manual("Tournament", -->
<!-- #                                 values = tournament_colors, -->
<!-- #                                 labels = c("Australian Open\n(Plexicushion)\n", -->
<!-- #                                            "French Open\n(Clay)\n", -->
<!-- #                                            "US Open\n(DecoTurf)\n", -->
<!-- #                                            "Wimbledon\n(Grass)\n")) + -->
<!-- # # + -->
<!-- # #   guides(color = guide_legend(override.aes = list(size = 7, shape=15))) +  -->
<!-- # facet_wrap(~tournament) + -->
<!-- # theme(legend.position="none") +  -->
<!-- #   ylim(c(-0.02, 0.2)) -->

<!-- p_wta_percent -->


<!-- ggarrange(p_atp_percent, NULL, p_wta_percent, common.legend = TRUE, legend="bottom", widths = c(1, 0.08, 1), nrow = 1)  -->

<!-- if(save_graph){ -->
<!-- ggsave("../plots/aces_median_percent_BW2_v2.jpg", height=8, width=graphic_width_long) -->
<!-- } -->

<!-- ``` -->

